- app/index.html
- app/templates/application.hbs
- package-lock.json
- package.json
Normally this is already installed in 3.24+ not sure why it wasn't.
> Set up ember-page-title

- app/controllers/people/index.js
- app/routes/people/index.js
- app/templates/people/index.hbs
- package.json
Since the API calls take a while to finish, waiting for the model hook to finish isn't very user friendly.
This change makes sure the page instantly renders and shows a loading state instead.
This follows a similar pattern as described here: https://engineering.linkedin.com/blog/2016/12/ember-concurrency--or--how-i-learned-to-stop-worrying-and-love-t
> Add "skeleton loading" to the people search page

- app/controllers/people/index.js
I noticed the pagination wasn't being reset when applying a new filter (or resetting).
> Reset the pagination when searching

- app/components/table-message/error.hbs
- app/controllers/administrative-units/index.js
- app/controllers/people/index.js
- app/templates/administrative-units/index.hbs
- app/templates/people/index.hbs
This shows a generic error message when something goes wrong while fetching data.
Screenshot:
> Search table error messages

- package-lock.json
- package.json
Not used right now, but it will be useful when we need to link to the user manuals, or when configuring mail addresses.
> Install ember-config-helper

- .prettierrc.js
Using prettier for .hbs files should now keep the double quotes.
> Prettier: Don't use single quotes for .hbs files

- config/environment.js
These shouldn't be needed in modern apps. If the array behavior is wanted it's better to create an ember array explicitly.
More information: https://guides.emberjs.com/release/configuring-ember/disabling-prototype-extensions/
> Disable prototype extensions

- app/templates/administrative-units/administrative-unit.hbs
- app/templates/administrative-units/administrative-unit/index.hbs
This makes sure the breadcrumb is visible on all subpages instead of only on the "core data" page.
> Move the administrative unit breadcrumb to the parent page

- config/deprecation-workflow.js
- package-lock.json
- package.json
This sets up ember-cli-deprecation workflow so deprecations triggered by some addons aren't visible.
> Set up ember-cli-deprecation-workflow

- .eslintrc.js
- app/router.js
This rule is outdated. Depending on the default model behavior is not recommended anymore.
> Disable the "ember/routes-segments-snake-case" rule project wide

- app/models/administrative-unit.js
It might be a good idea to do this for _all_ relationships that have an inverse. I think ember data is moving towards pushing people to always make that explicit. But for now we'll do it if we run into issues I guess :smile:.
> Add an explicit inverse to the scope relationship

- app/components/datepicker.hbs
- app/components/datepicker.js
This returns the actual date instance instead of the iso date string.
> Return a Date instance in the onChange action

- app/components/page-header.hbs
This can be used as a replacement for the copy pasted header structures.
Usage:
```hbs
<PageHeader>
<:title>Kerngegevens</:title>
<:subtitle>{{! optional}} {{@model.administrativeUnit.name}}</:subtitle>
<:action>
{{! optional}}
<AuLink
@route="administrative-units.administrative-unit.core-data.edit"
@skin="button-secondary"
@icon="pencil"
@iconAlignment="left"
>
Bewerk
</AuLink>
</:action>
<PageHeader>
```
> Create a `<PageHeader>` component

- app/models/administrative-unit.js
- app/models/agent-in-position.js
- app/models/associated-legal-structure.js
- app/models/change-event.js
- app/models/contact-point.js
- app/models/governing-body.js
- app/models/identifier.js
- app/models/local-involvement.js
- app/models/location.js
- app/models/mandate.js
- app/models/mandatory.js
- app/models/minister-condition.js
- app/models/minister-position.js
- app/models/minister.js
- app/models/organization.js
- app/models/person.js
- app/models/post.js
- app/models/representative-body.js
- app/models/site.js
- app/models/worship-administrative-unit.js
- app/models/worship-mandatory.js
- app/models/worship-service.js
I noticed a missing inverse related error message when clicking through the administrative units search pages so I decided to add it to all the relationships. Most of the changes are just formatting though.
More info: https://github.com/emberjs/rfcs/pull/739
Error message:
```
Uncaught Error: Assertion Failed: You defined the 'involvedBoards' relationship on model:worship-service, but you defined the inverse relationships of type model:local-involvement multiple times. Look at https://guides.emberjs.com/current/models/relationships/#toc_explicit-inverses for how to explicitly specify inverses
```
> Add explicit inverse relationship names

- app/templates/login.hbs
This makes it consistent with the other LBLOD apps and it looks way better on large screens.
Before:
After:
> Limit the width of the login page content

- app/components/person-search.hbs
- app/components/person-search.js
- app/styles/_shame.scss
The DataTable component doesn't support updating the page counter without 2-way-binding, which is a problem when it is not linked to a query parameter. Instead of using a bad workaround, it's better to disable pagination for now. Users will most likely search for a very specific person by typing their full name. This usually yields few enough results that pagination isn't strictly needed.
More information: https://github.com/mu-semtech/ember-data-table/issues/27
> Disable the pagination in the PersonSearch component

- app/routes/administrative-units/administrative-unit/local-involvements/index.js
This has the advantage that we can add sorting, filtering and pagination when needed.
> Use a query to fetch local involvements data

- app/routes/administrative-units/index.js
- app/routes/people/index.js
Changing query params adds a lot of history entries by default so pressing back doesn't work as expected.
> Don't update the browser history when changing filters

- app/templates/administrative-units/administrative-unit.hbs
To make sure we don't have to create new pages explaining why these pages do not exist just yet. We can show them again once the pages have been implemented – perhaps add a "new" label or a nice onboarding experience to the new feature.
> Temporarily hide links to unused pages

- app/controllers/administrative-units/administrative-unit/local-involvements/edit.js
- app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs
- Disable the edit button while saving
- Show a loading state while saving
- run the save calls in pararel to speed it up
> Local involvements edit page improvements

- app/components/edit-card.hbs
- app/components/edit-card/item.hbs
- app/controllers/administrative-units/administrative-unit/ministers/new.js
- app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
- app/templates/administrative-units/administrative-unit/ministers/new.hbs
This pr:
- prevents the users from creating a minister position before selecting a function role first
- adds required field styling as shown here: https://appuniversum.github.io/ember-appuniversum/docs/patterns/au-card-edit
- updates the previous implemented required field on the mandatory creation page
Note: This is temporary / quick validation fix. The real validation implementation will include error messages and other data validations.
> Some required fields updates

- app/initializers/analytics.js
- config/environment.js
- tests/unit/initializers/analytics-test.js
This script allows the specification of two environment variables through the docker-compose.override.yml.  When these are set correctly, plausible will be injected and logging will commence.
- `EMBER_ANALYTICS_APP_DOMAIN`: The domain for which the app should be monitored.
eg: example.abb.vlaanderen.be
- `EMBER_ANALYTICS_PLAUSIBLE_SCRIPT`: Full path to the plausible script on the server.
> Add plausible analytics script as built for gelinkt-notuleren

- app/redirect-handlers/administrative-unit.js
- app/redirect-handlers/person.js
- app/redirect-handlers/redirect-handler.js
- app/router.js
- app/routes/redirect.js
- app/services/deep-link.js
- app/services/uri-info.js
- config/environment.js
- tests/unit/routes/redirect-test.js
- tests/unit/services/deep-link-test.js
- tests/unit/services/uri-info-test.js
This implements direct linking to people and "worship administrative units".
It can be tested by using the following url: `http://localhost:4200/redirect?resource=add-resource-uri-here`
If the type of the resource is supported it should go to the correct page, else it will show the index page instead for now.
Requires this branch in the backend app: https://github.com/lblod/app-contact-hub/pull/57
> Deep linking support

- app/components/address-register-selector.js
- app/components/address-search.hbs
- app/components/address-search.js
I missed this in the PR. The address data wasn't visible when in "search mode" which is confusing. Now it shows the existing address data.
> Show the existing address in the address search box

- app/components/address-search.hbs
- app/components/data-card/item.hbs
- app/components/edit-card/item.hbs
- app/styles/components/_cards.scss
- app/templates/administrative-units/administrative-unit/core-data/index.hbs
- app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
- app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
- app/templates/administrative-units/administrative-unit/ministers/new.hbs
- app/templates/organizations/organization/index.hbs
- app/templates/people/person/positions/minister/edit.hbs
The label isn't always needed and this allows us to remove the empty label elements that we used as a workaround.
> Make the Card::Item label optional

- app/controllers/administrative-units/administrative-unit/core-data/index.js
- app/templates/administrative-units/administrative-unit/core-data/index.hbs
This adds SharePoint links to the worship administrative unit details page. This allows users to more easily verify if the data was imported correctly.
> Add links to SharePoint

- config/environment.js
The 'AutoLocation' class is used by default and is needed to support older browsers that don't have access to the History api. We don't need to support old browsers so we can use the 'HistoryLocation' class instead. 'AutoLocation' will also be deprecated soon.
> Use 'history' instead of 'auto'

- app/routes/administrative-units/administrative-unit/core-data/edit.js
We have logic in place that creates missing identifiers when entering the edit page. This logic wasn't working correctly which sometimes causes an exception during the route transition.
> Fix a problem which prevents users from entering the core data edit page

- app/components/address-search.hbs
- app/templates/administrative-units/administrative-unit/core-data/edit.hbs
- app/templates/administrative-units/administrative-unit/sites/new.hbs
- app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
- app/templates/administrative-units/new.hbs
- app/validations/address.js
When integrating CRAB we removed the requirement to fill in a province since this information is not provided by CRAB. End users still expect the province to be there for administrative units since they can filter the search using that data. So this adds back the requirement for certain pages.
> Province is a required field on some pages

- app/components/address-search.hbs
The link wasn't working correctly so clicking it didn't prefill the email field with the correct address.
> Fix "Mail ons" link in the address search functionality

- .release-it.json
GITHUB_AUTH is also used by lerna-changelog so this means only 1 token needs to be added to the command.
More information can be found on [the release-it automated Github release guide](https://github.com/release-it/release-it/blob/master/docs/github-releases.md#automated).
> Use GITHUB_AUTH for release-it

- app/controllers/administrative-units/administrative-unit/change-events/index.js
- app/models/change-event-result.js
- app/models/change-event.js
- app/models/organization.js
- app/router.js
- app/routes/administrative-units/administrative-unit/change-events.js
- app/routes/administrative-units/administrative-unit/change-events/index.js
- app/templates/administrative-units/administrative-unit.hbs
- app/templates/administrative-units/administrative-unit/change-events.hbs
- app/templates/administrative-units/administrative-unit/change-events/index.hbs
Targeting the `feature/change-events-management` branch instead of `development` so that we can merge and deploy that branch when the database is migrated.
It requires this branch in the backend: https://github.com/lblod/app-contact-hub/pull/75
> Implement the change event overview page

- app/models/change-event.js
- app/models/organization.js
- app/routes/administrative-units/administrative-unit/change-events/details/index.js
- app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
The previous naming was confusing since it implied that it was a 1 to 1 relationship.
> Pluralize the hasMany relationship names

- package-lock.json
- package.json
This addon overwrites the `date` transform from Ember Data with a version which only serializes the date itself (not the time). This is what we need for most of our datepickers.
No other code changes are needed since we already use the `date` transform.
> Install ember-mu-transform-helpers

- app/controllers/administrative-units/administrative-unit/change-events/new.js
- app/routes/administrative-units/administrative-unit/change-events/details/edit.js
- app/routes/administrative-units/administrative-unit/change-events/new.js
I noticed some things were missing in the previous implementations:
- only save decisions if the change event type requires it
- update the edit page so that it doesn't require a decision record if it's not needed
- clean up unsaved records when leaving the creation page
> Some small change event improvements

- app/controllers/administrative-units/administrative-unit/change-events/new.js
- app/routes/administrative-units/administrative-unit/change-events/new.js
- app/templates/administrative-units/administrative-unit/change-events/new.hbs
Selecting more than 1 original organization is no longer a requirement for the "gebiedswijziging" change event.
> Improve the original organizations selection logic on the change events creation page

- app/controllers/administrative-units/administrative-unit/local-involvements/edit.js
- app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs
- package-lock.json
- package.json
We now check if there are any financial organizations before triggering the total percentage validation. This fixes a problem were a valid form was marked invalid and prevented users from saving.
> Fix a problem were saving doesn't work on the local involvements page

- ember-cli-build.js
The page shows a white screen due to missing assets. This is caused by the ember-auto-import 2.4.0 release which outputs css files instead of js with bundled css. The problem is that these css files are fingerprinted by default, which means the filename doesn't match the importmap value.
This adds configuration to make sure the chunked css files aren't fingerprinted.
More information: https://github.com/ef4/ember-auto-import/pull/496/files
> Fix the SPARQL page

- app/controllers/people/person/personal-information/edit.js
- app/routes/people/person/personal-information.js
- app/routes/people/person/personal-information/edit.js
For some position, when you try to edit them, you get an error (e.g => https://dev.organisaties.abb.lblod.info/personen/19a4d659d73809129467ac1c39e7fd02/contactgegevens )
This PR is an attempt to fix it. As we mix two kinds of resources (mandates, ministers), I had to work around a little bit.
> Fix Edit page when primary contact is null

- app/components/change-event-type-select.hbs
Even if we don't allow the search, we have to define this property otherwise when power select is open and we type something an error occurs.
> Add searchField to power select

- app/routes/administrative-units/index.js
This fixes OP-1222's comment from Zelim.
I tested directly with dev data with `ember serve --proxy=https://dev.organisaties.abb.lblod.info`
> Handle special characters in search

- app/controllers/organizations/organization/related-organizations.js
- app/routes/organizations/organization/related-organizations.js
- app/templates/organizations/organization/related-organizations.hbs
The branch name is misleading sorry, goal was to add a loading state in the related organization tabs (ex. Bisdom Gent) and it has the form of a message, not dancing dots.
Solves OP-1271
> Show a message when data is loading in related orgs tab

- app/components/contact-details.hbs
- app/components/contact-details.js
see OP-1364.
to reproduce:
- check for a position with invalid contact details
- example: http://localhost:4200/bestuurseenheden/4c03829486377310ada8bf402bb591be/bestuursorganen/513431c6618f670fc069b3512f789799/mandataris/4f03f3797a22d2a7c4e9580474a069cf
- try to select one (copy it)
- it should now open the popup and force you to edit it before being able to select it
> fix contact details copy with invalid existing data

- app/templates/people/person/personal-information/request-sensitive-data.hbs
As discovered in the chat during CPD20
> Fix typo in page header title

- app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/edit.js
- app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
seems fixing OP-1352's comment of kevin:
When you press ‘Annuleer’ when no edits were made > you’re brought back to the previous page. (OK) :check_mark:
When you press ‘Annuleer’ when edits were made > undoes the edits (OK) :check_mark: but doesn’t bring the user back to the previous page (even with repeated clicking the button) (NOK) :minus:
> fix weird behavior with aulink

- app/templates/application.hbs
- config/environment.js
OP-1430
to test:
- Build locally the frontend
- add env variable ::
```
EMBER_ANNOUNCE_MAINTENANCE_ENABLED: "true" 
EMBER_ANNOUNCE_MAINTENANCE_MESSAGE: "(f.e. Het OrganisatiePortaal zal donderdag 24/03 tussen 12:00 en 15.00 u. onbeschikbaar zijn wegens onderhoud)"
```
```
EMBER_ANNOUNCE_NEW_DEPLOYMENT_ENABLED:  "true"
EMBER_ANNOUNCE_NEW_DEPLOYMENT_MESSAGE:  "(f.e. Het OrganisatiePortaal zal vanaf donderdag 24/03, 19.00 uur t.e.m. vrijdag 25/03 8.00 uur onbeschikbaar zijn wegens de uitrol van een nieuwe versie)" 
```
```
#to show the testing message
EMBER_ANNOUNCE_TESTING_ENABLED: "true"
EMBER_ANNOUNCE_TESTING_MESSAGE: "(f.e. Het OrganisatiePortaal zal vandaag, donderdag 24/03, niet stabiel zijn wegens uitvoering van testen.)"
```
> message announcement

- app/styles/_shame.scss
- app/styles/app.scss
- app/templates/application.hbs
FYI @iurianu 
It will have to be fixed to
1. not show the banner on prod
2. not have a gap in the top of the page when no banner is shown
3. fix the {{ENVIRONMENT_TITLE}} value on QA
> Hotfix revert banner - showing on prod

- app/controllers/administrative-units/new.js
- app/models/administrative-unit.js
- app/templates/administrative-units/administrative-unit/core-data/edit.hbs
- app/templates/administrative-units/administrative-unit/core-data/index.hbs
- app/templates/administrative-units/new.hbs
Refer to the region instead of the municipality working area.
The municipality working area is located within the region.
Note that the first iteration uses an implicit reference to the higher level, a possible improvement is to check whether that higher level is a `Referentieregio`.
> Fix references to region vs municipatily

- app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/index.js
- app/controllers/administrative-units/administrative-unit/ministers/index.js
- app/controllers/people/new-position.js
- app/controllers/people/person/personal-information/index.js
- app/controllers/people/person/positions/mandatory/index.js
- app/controllers/people/person/positions/minister/index.js
- app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.js
- app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.js
- app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
- app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
- app/routes/administrative-units/administrative-unit/ministers/new.js
- app/routes/people/person/personal-information/edit.js
- app/routes/people/person/positions/minister/edit.js
- app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
- app/templates/administrative-units/administrative-unit/ministers/index.hbs
- app/templates/people/index.hbs
- app/templates/people/new-position.hbs
- app/templates/people/person/personal-information/index.hbs
- app/templates/people/person/positions/mandatory/index.hbs
- app/templates/people/person/positions/minister/index.hbs
OP-2032
This will not be testable by the testers, what I did to test locally was to update the `new Date('2023-02-01')` by today's date.
As it'll not be tested by the testers, an extensive testing of this one would be valuable :smile: Thanks !
> Disable position creation or edition from 01/02/2023

- app/validations/administrative-unit.js
A validation checking if a municipality had a `wasFoundedByOrganization` relation (that never exists for this type of admin unit) prevented the user to save a municipality. This PR fixes it.
OP-2555
> Fix validations too strict on municipalities

- app/components/administrative-unit-select-by-name.js
The classification identifiers for the new kind of units were missing, causing them not to show up as completion suggestions when searching by name.
> Added new classification identifiers to select by name

- app/components/administrative-unit-select-by-name.js
- app/routes/administrative-units/index.js
- app/utils/classification-identifiers.js
As a follow-up to #512 I moved the duplicated code to a util to prevent similar oversights in the future.
> Moved duplicate classification identifier selection to util

- app/helpers/format-identifier.js
OP-2747: allow underscores in search string as they are used for SharePoint identifiers
> Allow underscores in identifier search field

- app/components/error/save.hbs
- app/controllers/administrative-units/administrative-unit/change-events/details/edit.js
- app/controllers/administrative-units/administrative-unit/change-events/new.js
- app/controllers/administrative-units/administrative-unit/core-data/edit.js
- app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/edit.js
- app/controllers/administrative-units/administrative-unit/local-involvements/edit.js
- app/controllers/administrative-units/administrative-unit/related-organizations/edit.js
- app/controllers/administrative-units/administrative-unit/sites/new.js
- app/controllers/administrative-units/administrative-unit/sites/site/edit.js
- app/controllers/administrative-units/new.js
- app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
- app/templates/administrative-units/administrative-unit/change-events/new.hbs
- app/templates/administrative-units/administrative-unit/core-data/edit.hbs
- app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.hbs
- app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
- app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs
- app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
- app/templates/administrative-units/administrative-unit/sites/new.hbs
- app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
- app/templates/administrative-units/new.hbs
OP-2661
Some pointers on which changes are relevant:
- Templates
- Added a new component `Error::Save`, typically right under the `AuButtonGroup`
- Where necessary configured right alignment for the buttons and/or the message(s) shown underneath.
- Controllers
- Added a getter `hasValidationErrors` used to determine whether or not to show the overall error message. The body of this getter is derived from the if-condition in the `save` (or similar) function in the same controller.
- Other changes are purely formatting performed by an (overly) eager local instance of prettier.
Note that I only modified pages with forms that are currently accessible to users to avoid introducing bugs that might remain unnoticed for a long time. Most forms for adding and/or editing persons (and their …
> Feature: show error message underneath save button when a form contains errors

- app/components/administrative-unit-select-by-identifier.hbs
- app/components/administrative-unit-select-by-identifier.js
- app/helpers/format-identifier.js
- app/routes/administrative-units/index.js
OP-2725
Changes to match identifiers based only on their alphanumeric characters using a new `index` field introduced in the backend.
The previous PR including underscores as allowed input was still buggy for identifiers containing other non-alphanumeric characters such as dashes and brackets.
> Fix: use only alphanumeric characters to match identifiers

- app/components/site-type-select.js
OP-2777
Seems like the issue was that the loading was sometimes called before the getters could fully resolve the model, causing in those situations the filtering of the types to not be working as expected. Adding a small timeout prevents it.
> Add timeout when loading site types

- app/components/province-organization-select.hbs
- app/controllers/administrative-units/administrative-unit/core-data/edit.js
- app/templates/administrative-units/administrative-unit/core-data/edit.hbs
OP-2788
On first load or after a refresh, `this.selectedProvince` and `this.selectedMunicipality` were not set, causing the conditional selection not to work.
> Fix selected province and municipality in core data related orgs

- app/templates/people/person/positions/agent/index.hbs
OP-2831
Note, only functional change is the removal of the if-then-else clause in the second commit, other changes are purely code formatting.
> Fix: make names of AGB, APB, and IGS clickable on positions page

- app/styles/_shame.scss
So this is related to OP-2854, the line avoiding the power select to go full height was defined in appuniversum, as it was set to a max-width of 10rem, I assumed this is something we only want to do in the classification power select, so I restricted it to only be there, but if you think we want this behaviour on all the multiple power select I can change it
> Avoid scrolling in multiple select on classifcation

- .woodpecker/.feature.yml
Add Docker image build whenever a push event occurs on a `feature/*` branch.
> CI - Add .woodpecker/.feature.yml configuration file

- README.md
- app/helpers/is-feature-enabled.js
- app/services/features.js
- config/environment.js
- tests/unit/services/features-test.js
Import Feature flag service and helper from [Lokaal Beslist](https://github.com/lblod/frontend-burgernabije-besluitendatabank/tree/master#feature-flags). 
1. Define a new flag in the [config/environment.js](https://github.com/lblod/frontend-organization-portal/blob/master/config/environment.js)
```javascript
// in config/environment.js
let ENV = {
// Other configuration settings...
features: {
"new-feature": true, // Enable the 'new-feature' by default
"beta-feature": false, // Disable the 'beta-feature' by default
},
};
```
2. Wrap your modifications behind the flag : 
With the service in router/controller/components
```javascript
import { inject as service } from "@ember/service";
export default class ExampleComponent extends Component {
@service features;
doSomething() {
if …
```
> Add feature flag service and helper

- app/controllers/administrative-units/administrative-unit/core-data/edit.js
- app/controllers/administrative-units/new.js
In https://github.com/lblod/frontend-organization-portal/pull/554 we move validation to `identifier` instead of `structuredIdentifier`. `hasValidationErrors` in controller needed to be updated also in order to prevent form submission when `identifierKBO` or `identifierSharepoint` is wrong.
> Use identifier instead of structuredIdentifier to detect error

- app/routes/administrative-units/administrative-unit/core-data/edit.js
Related to OP-2814
https://github.com/lblod/frontend-organization-portal/pull/554 introduces a bug when we exiting edit route. Model changes in /edit are not undone before calling the /index `model` hook, this may cause errors. 
- Edit an administrative unit
- Switch to manual address `Vul adres manueel in`
- Remove municipality
- cancel edition by clicking on `Annuleer`
You are redirected to `/pagina-niet-gevonden` due to error (`TypeError: municipalityUnit is undefined`
) in route `administrative-units.administrative-unit.core-data.index` `model` hook. 
Move `controller.reset()`, that undo all model changes, in `administrative-units.administrative-unit.core-data.edit` `willTransition` hook instead of `resetController`. 
Clicking on the `Annuleer` button will initiate transition from …
> Fix reseting controller when exiting `administrative-units.administrative-unit.core-data.edit`

- app/routes/administrative-units/administrative-unit/core-data.js
Related to OP-2937
`wasFoundedByOrganizations` is a required field by some forms like AGB or APB. 
https://github.com/lblod/frontend-organization-portal/blob/c4283ee4a7a2d46672e7e079c47732a02c0b17da/app/models/administrative-unit.js#L79-L87
Because `wasFoundedByOrganizations` is not directly used in the form, except when editing the relation. https://github.com/lblod/frontend-organization-portal/blob/c4283ee4a7a2d46672e7e079c47732a02c0b17da/app/controllers/administrative-units/administrative-unit/core-data/edit.js#L77-L98
The value of `wasFoundedByOrganizations` is not available the first validate call, then return an error. 
Force loading `wasFoundedByOrganizations` by adding it in the require field when the `administrative-unit` is loaded.
> Fix AGB/APB edit form validation

- app/models/worship-service.js
`mu-cl-resources` returns the most specific type. For example, when you request an `adminstrative-unit`, you can receive in response a `worship-service`. It's the case when you want edit a `Bestuur van de eredienst`. 
In that case, when you submit the edit form, you get an error message because the model contains more properties than the `administrative-unit` validationSchema accept. 
Add `validationSchema` on `WorshipServiceModel`.
> Fix administrative-unit edit validtion on WorshipService

- app/templates/administrative-units/administrative-unit/core-data/edit.hbs
Related to OP-3047
The reported bug also revealed that the edit core data form contains insufficient fields in case the organisation being edited is a PEVA municipality or PEVA province. More specifically, the form lacks the related organizations part in such case. This PR corrects this particular form so that it shows the correct fields for both types of PEVAs. 
Note: this PR is **not** intended to fix the reported bug itself, i.e. the inability to edit core data of PEVAs that do not have a founding organisation.
> Fix: show related organisations in edit core data form for PEVAs

- app/controllers/administrative-units/administrative-unit/core-data/edit.js
- app/models/abstract-validation-model.js
- app/models/administrative-unit.js
- app/templates/administrative-units/administrative-unit/core-data/edit.hbs
- tests/unit/models/administrative-unit-test.js
OP-3051
Related to the bugs reported in OP-3046 and OP-3047
While a founding organisation should be mandatory for OCMW associations and PEVAs the available business data is incomplete. Strictly enforcing this rule would thus mean that units lacking a founder at the time of onboarding cannot be edited later on as their validation will fail. This commit relaxes this rule such that a founding organisation is only required when creating a new OCMW association or PEVA via the frontend.
> Fix: relax requirement of founding organization for newly onboarded unit types

- app/routes/administrative-units/administrative-unit/change-events/details.js
- app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
- app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
The syntax use to replace `firstObject` during update to ember 4.12 : `{{get @model.changeEvent.resultingOrganizations "0.name"}}`
Although, this syntax is describe in `no-array-prototype-extensions` linter documentation it is not working on a promise proxy arrays. https://github.com/emberjs/ember.js/issues/20510
Resolve the firstObject in the route
> Fix change-event resulting organization name

- app/controllers/administrative-units/administrative-unit/core-data/edit.js
Related to OP-3048
KBO and Sharepoint were not correctly reset in administrative-unit edit form controller.
> Fix sharepoint and kbo reset in administrative-unit edit form

- package-lock.json
- package.json
Related to OP-3065
KBO-number shouldn't be checked if the value hasn't change. https://github.com/lblod/frontend-organization-portal/blob/development/app/models/identifier.js#L41-L44
The previous ember update introduce a bug in `changedAttributes` result after saving https://github.com/emberjs/data/issues/8329
Bump to ember-data 4.12.5 fixes the problem.
> Update ember-data version to 4.12.0

- app/components/administrative-unit-select-by-name.js
- app/controllers/administrative-units/administrative-unit/core-data/edit.js
- app/helpers/help-text.js
- app/models/organization.js
- app/routes/administrative-units/index.js
- app/templates/administrative-units/administrative-unit/core-data/edit.hbs
- app/templates/administrative-units/administrative-unit/core-data/index.hbs
- app/templates/administrative-units/new.hbs
- app/templates/organizations/organization/core-data.hbs
OP-3000
- Added field "Alternatieve naam" to core data views, only visible when at least one alternative name was set
- Extended edit core data and create administrative unit forms with an input field for alternative names. Multiple names should be separated by a comma.
- Added a custom transformation to convert string displayed for alternative names in the forms to an array of strings that can be processed by the backend (and vice versa)
- Inlude the alternative names in the name search (requires a reindex to work)
- Backend [PR](https://github.com/lblod/app-organization-portal/pull/390)
> Feature: add alternative names for organisations

- app/controllers/administrative-units/new.js
- app/templates/administrative-units/new.hbs
OP-3099
This bug reported two things
- Validation error during creation: this was fixed by correcting the form to correctly set the new alternative names
- An error appeared in the console when trying to edit "A.S.Z. Autonome Verzorgingsinstelling". The underlying cause was that  this organisation had as alternative name the **numeric value** 1 saved in the triplestore instead of a string literal. But I was unable to replicate this situation for another organisation via the frontend. The only way I was able to somewhat replicate it was by directly inserting a numeric value into the triplestore using the SPARQL endpoint. I ended up removing the faulty value for this specific organisation in the DEV environment,via the frontend by clearing its alternative name field and saving the form. …
> Fix: correctly set alternative names when creating new administrative units

- app/models/agent-in-position.js
- app/models/person.js
The update in #589 introduced a bug where the frontend crashed upon opening a page concernig people. For example, opening the "Leidinggevenden" tab for the municipality of Leuven resulted in the following error:
```
Error: The schema for the relationship 'functionary.person' is not configured to satisfy 'agent-in-position' and thus cannot utilize the 'agent-in-position.person' relationship to connect with 'person.agentsInPosition'
If using this relationship in a polymorphic manner is desired, the relationships schema definition for 'functionary' should include:
{
person: {
name: 'person',
type: 'person',
kind: 'belongsTo',
options: {
as: 'undefined', <---- should be 'agent-in-position'
async: true,
polymorphic: false,
inverse: 'agentsInPosition'
}
}
}
and the relationships schema …
```
> fix: make relation between Person and AgentInPosition polymorphic

- app/controllers/administrative-units/new.js
OP-3129
The juridical name and alternative names were not explicitly copied to the `newAdministrativeUnit` object that would eventually be saved. Consequently, these names were lost upon saving a worship administrative unit. For non-worship administrative units this did not occur because the created record was reused.
> Fix: explicitly copy legal and alternative names when creating new units

- app/models/identifier.js
- tests/unit/models/identifier-test.js
> Fix: Validate Sharepoint identifier only when modified

- app/controllers/administrative-units/administrative-unit/core-data/edit.js
- app/models/identifier.js
- tests/unit/models/identifier-test.js
OP-3147
Note: the second commit is a quick fix for another bug encountered in the process of solving the original one. I think a cleaner solution for that requires more in-depth changes.
> Do not trigger validation on empty SharePoint identifier

- app/controllers/administrative-units/administrative-unit/core-data/index.js
This typo caused the match to fail for OCMW associations resulting in using the wrong link.
> fix: Corrected typo in function call

- app/models/administrative-unit.js
- app/models/central-worship-service.js
- app/models/worship-administrative-unit.js
- app/models/worship-service.js
- tests/unit/models/administrative-unit-test.js
- tests/unit/models/central-worship-service-test.js
- tests/unit/models/worship-administrative-unit-test.js
- tests/unit/models/worship-service-test.js
Bug reported by @cecemel that prevents the creation of new worship
services. Also reported by the testers (OP-3178) shortly after the initial
report.
The form for new organizations uses an administrative-unit record. This means
that if the functions are placed in the more specific models they cannot be
correctly used when deciding which fields to show.
More concretely, the fields for "Soort eredienst", "Strekking", and
"Grensoverschrijdend" were not shown when creating worship services. The
get-functions used to trigger displaying these fields were defined in the
worship service model and therefore not available in the form.
Note: While fixing this bug I noticed a similar problem with the "Centraal
bestuur" field that is never shown. This bug was introduced in earlier
refactoring and …
> fix: moved worship classification checks to administrative unit model

- app/models/worship-administrative-unit.js
- app/templates/organizations/new.hbs
OP-3177
The field "Centraal bestuur" was previously never shown in the necessary forms (create new organization and edit related organizations) as a consequence of two issues:
1. The `hasRecognizedWorshipTypeId` function in `worship-adminsitrative-unit` contained a bug in that it used the `classification` relation instead of the `recognizedWorshipType` relation.
2. The template for the new organizations form operates on a plain `administrative-unit` model instance and has no access to the `hasCentralWorshipService` getter in `worship-administrative-unit`.
1. The first problem was simply fixed by correcting the implementation of the function. (commit 135dca9d)
2. The second problem was worked around by explicitly implementing the necessary check in the template. (commit 60a62397) As …
> fix: display field for "Centraal bestuur" in appropriate forms

- app/components/kbo-organization/data-card.hbs
- app/components/kbo-organization/data-card.js
> Add message when kboOrganization is missing

- app/controllers/organizations/new.js
- app/models/administrative-unit.js
- app/models/central-worship-service.js
- app/models/worship-administrative-unit.js
- app/models/worship-service.js
- app/routes/organizations/new.js
- app/templates/organizations/new.hbs
Previously the functionality for creating new organisations mainly operated on the `AdministrativeUnitModel`. This PR makes that functionality more dynamic such that it always uses the most specific organisation model type depending on the classification selected by the user.
- OP-3183: this refactoring brings also a better fix for that bug than was proposed in #609
- OP-3026: these changes should make it easier to extend the organisation creation functionality to non-administrative unit organisations
The organisation model instances available in the new organisation route were create a priori by the router. Any input provided by the user was assigned to the generic `AdministrativeUnitModel` instance. Only after this model was successfully validated were the user inputs copied to one of …
> Generalise organisation creation to operate on the most specific model type

- app/components/kbo-organization/data-card.hbs
- app/templates/administrative-units/administrative-unit/core-data/index.hbs
- app/templates/organizations/organization/core-data.hbs
Related to OP-3220
Fix the warning message displays when the organization has a KBO Identifier but no `localId` value.
> Fix Missing kbo number message

- app/models/representative-body-classification-code.js
Related to OP-3229
The representative body classification codes was recently fixed in the triplestore by https://github.com/lblod/app-organization-portal/pull/412
As a side effect, a code typed `representative-body-classification-codes` is part of `/organization-classification-codes` response. The app is complaining because the model is missing. 
Adding the missing model.
> Add missing `representative-body-classification-codes` model

- app/controllers/organizations/organization/change-events/details/edit.js
- app/models/decision.js
Related to OP-3001
The underlying problem for the reported bug was that removing the document link resulted in an empty decision. This empty decision was ignored when saving the edited change event, as a result the user's edits were forgotten and the old decision was kept as is.
In the course of investigating this ticket a related problem was encountered. When a user added decision information (document link and/or decision date) to a change event that did not had a decision yet, these edits were also ignored. The underlying cause was that adding a new decision is not detected by `hasDirtyAttributes`. Consequently, the change event, with its newly set decision, was not saved (unless another attribute was changed as well).
To correctly deal with **removed** decisions, when the decision is …
> fix: correctly update change event decisions after editing

- app/templates/organizations/new.hbs
The new organisation form contained a bug where the `denomination` and
`crossBorder` properties were not set on the `currentOrganizationModel`
introduced in #611.
Note, these properties are not copied when switching models as they are
exclusive to worship services.
> fix: set properties on correct model

- app/models/organization.js
- tests/unit/models/organization-test.js
Related to OP-2286
With the introduction of the different organisation names it was intended to use
the KBO organization's name as a fallback value when no legal name is set. But
when this additional name functionality was added the KBO/wegwijs service was
not yet finished and the name variable was used as only fallback.
This resolves the leftover TODO and adds the KBO organization's name as first
fallback value for the `abbName` getter.
> feature: use KBO organization's name as first fallback

- app/routes/organizations/organization/core-data/edit.js
- app/templates/organizations/organization/core-data/edit.hbs
Previously the region was not loaded in the model for PEVAs and the field was
not shown in the core data edit form. These changes correct this to align the
behaviour with the new organisation form as well as the core data editing for
other kinds of organizations.
> fix: correctly include region when editing a PEVA

- app/templates/organizations/new.hbs
Related to OP-3177 and OP-3183
In #608 a dirty hack was applied to resolve a bug were the central worship
service field was not shown when appropriate. Now that the new organisation
handles the different model types in a proper manner this (see #611) this quick
fix can be replaced by the proper function call.
> refactor: resolved fixme central worship service field

- app/services/deep-link.js
Related to OP-3279 and KAL-7826
The deep-link service was only configured to handle (central) worship services
and persons. This extends that to all types of organizations.
Examples that can be used for testing, not that you have to be logged with the
appropriate role:
- localhost:4200/redirect?resource=http://data.lblod.info/id/besturenVanDeEredienst/62B9BBA5D7779543F7779555
- localhost:4200/redirect?resource=http://data.lblod.info/id/bestuurseenheden/ba4d960fe3e01984e15fd0b141028bab8f2b9b240bf1e5ab639ba0d7fe4dc522
> fix: redirect for all organizations

- app/controllers/organizations/organization/local-involvements/edit.js
- app/models/local-involvement.js
- app/models/worship-administrative-unit.js
- app/templates/organizations/organization/local-involvements/edit.hbs
- tests/unit/models/local-involvement-test.js
OP-3185 and OP-2993
Primary changes:
- Validate financing percentage for mid financing (*nl. mede-financierend*)
local involvements.
- Move the validation whether there is a supervisory (*nl. toezichtoudend*)
local involvement to the model and enforce there always is a supervisory local
involvement.
- Move total percentage validation into the model and take mid financing local
involvements into consideration.
> fix: improve local involvement validations

- app/helpers/join-array.js
- app/templates/organizations/organization/core-data/index.hbs
- tests/integration/helpers/join-array-test.js
An organization can have multiple alternative names. We display this list in a template directly, which causes the VM to call `.toString` on it which defaults to joining the array elements without any whitespace.
This adds a new `join-array` helper that can use different separators to join the array.
> [OP-3325] Add whitespace between each alternative name item

- app/components/change-event-type-select.js
`store.findAll` doesn't wait for the background reload to finish if the store already contains records of the specific type that is requested. Since we only run the `loadChangeEventTypesTask` on component creation, the full data set is never used.
By adding the `reload` option we ensure that the full dataset is loaded properly.
> [OP-3352] Fix an issue where the change event select options weren't always properly loaded

- app/components/app-header.hbs
- app/components/datepicker.hbs
- app/components/related-organizations-view-table.hbs
- app/components/trim-input.hbs
- app/controllers/organizations/new.js
- app/controllers/organizations/organization/core-data/edit.js
- app/helpers/boolean.js
- app/helpers/event-value.js
- app/styles/app.scss
- app/templates/application.hbs
- app/templates/mock-login.hbs
- app/templates/organizations/index.hbs
- app/templates/organizations/new.hbs
- app/templates/organizations/organization/change-events/details/edit.hbs
- app/templates/organizations/organization/change-events/new.hbs
- app/templates/organizations/organization/core-data/edit.hbs
- app/templates/organizations/organization/core-data/index.hbs
- app/templates/organizations/organization/governing-bodies/governing-body/edit.hbs
- app/templates/organizations/organization/local-involvements/edit.hbs
- app/templates/organizations/organization/related-organizations/index.hbs
- app/templates/organizations/organization/sites/new.hbs
- app/templates/organizations/organization/sites/site/edit.hbs
- app/templates/people/index.hbs
- app/templates/select-role.hbs
- ember-cli-build.js
- package-lock.json
- package.json
- tests/integration/helpers/event-value-test.js
This resolves all v2 deprecations following the [deprecation guide](https://github.com/appuniversum/ember-appuniversum/pull/459) and updates to Appuniversum v3.
**Notes:**
Appuniversum v3 introduced a new `AuLoader` deprecation, but this PR doesn't resolve that yet since it doesn't break anything and I didn't want to scope creep the PR.
> [OP-3343] Appuniversum v3 update

- app/app.js
- app/controllers/organizations/new.js
- app/controllers/organizations/organization/core-data/index.js
- app/helpers/has-many-value.js
- app/models/membership-role.js
- app/routes/organizations/new.js
- app/templates/organizations/organization/change-events/new.hbs
- app/utils/ember-data.js
- config/deprecation-workflow.js
- ember-cli-build.js
- tests/unit/helpers/has-many-value-test.js
- tests/unit/models/abstract-validation-model-test.js
- tests/unit/models/membership-test.js
This resolves any EmberData related deprecations I could find.
I clicked through the app as best as I could, but I'm unfamiliar with the app so I might have missed some flows.
To make testing easier, you could use the following deprecation-workflow config to hide the noisy non-EmberData deprecations:
<details>
<summary>Config</summary>
```js
self.deprecationWorkflow.config = {
workflow: [
// TODO: resolve before updating to Appuniversum v4
{
handler: 'silence',
matchId: '@appuniversum/ember-appuniversum.au-loader-visible-by-default',
},
// TODO: resolve before updating to Appuniversum v4
{
handler: 'silence',
matchId: '@appuniversum/ember-appuniversum.au-button-loading-message',
},
{ handler: 'silence', matchId: 'ember-resources.util.trackedTask' }, // TODO: Resolve before updating …
```
> [OP-3042] Resolve ember v4 deprecations

- app/models/local-involvement.js
- tests/unit/models/local-involvement-test.js
The validation that the total sum of financing percentages for local involvements is exactly 100 contained an error where any newly added local involvements were not considered in the calculation.
1. Log in as worship editor
2. Select a worship service in the organisation overview
3. Navigate to the “Betrokken lokale besturen” page
4. Click the “Bewerk” button in the top right corner
5. Add a new local involvement by clicking the “+ Voeg nieuw betrokken lokaal bestuur toe” button on the bottom
6. Fill in the necessary fields: select “Mede-financierend” as type of involvement, enter a percentage above 0
7. Make sure the total sum of the percentages equals 100
8. Click the save button in the top right corner
9. On most percentage fields an error should be shown concerning an incorrect total …
> fix: correctly calculate total sum of finance percentages for local involvements

- app/controllers/organizations/organization/related-organizations/edit.js
- app/models/administrative-unit.js
Memberships were not actually removed from the `memberships` array, only the
record was deleted. As a result an `TypeError` was thrown when trying to save
the form after adding and removing a new membership. This error was caused by
the `save` function trying to validate the deleted the membership record as it
is still referenced by the `memberships` array. Explicitly removing a membership
from the `memberships` array before deleting the record fixes this issue.
0. Make sure your browser's developer console is open
1. Select an organisation and navigate to its “Gerelateerde organisaties” page.
2. Click the edit button in the top right corner.
3. Add a new membership using the “+ Voeg nieuwe gerelateerde organisatie toe”
button on the bottom of the edit form.
4. Remove the newly added …
> fix: remove membership from array before destroying record

- app/constants/memberships.js
- tests/unit/models/administrative-unit-test.js
- tests/unit/models/organization-test.js
Previously the relationships that could be defined for provinces were incomplete. As a result a user could not add relationships involving provinces. This PR corrects this situation by allowing additional relationships for provinces.
A province can act as a member in the following types of memberships:
| Membership role | Organisation classification |
| --- | ---|
| is founder of | APB |
| is founder of | PEVA province |
| participates in | APB |
| has a relation with | APB |
| has a relation with | municipality |
| has a relation with | district |
| has a relation with | PEVA province |
| has a relation with | OCMW |
A province **cannot** have a
- founding organisation
- participant
- OP-3324
> fix: corrected the possible relationships between provinces and other organisations

- app/controllers/organizations/organization/related-organizations/edit.js
The logic to check and correct the `member` and `organization` assignments
before saving `memberships` has the unintended side effect of converting this
from an EmberArray to a regular one.  As a result, any edit after an
unsuccessful save will throw a `TypeError`s as the used `pushObject` and
`removeObject` functions are not defined for regular arrays.
To fix this `memberships` is reconverted to an EmberArray before further
processing within the `save` function.
0. Open the browser’s developer console.
1. Log in to OP with editor rights
2. Select an organization from the overview table on the index page
3. Navigate to the selected organization’s “Gerelateerde organisaties” page
4. Click the edit button in the top right corner
5. Click the “+ Voeg nieuwe gerelateerde organisatie toe” on …
> fix: ensure `memberships` is an EmberArray while it can be edited

- app/models/registered-organization.js
- tests/unit/models/registered-organization-test.js
OP-3388
Fixes the bug when creating new verenigingen or vennootschappen of failing validations. The memberships validations was too strict and was mandatory for every type, but since verenigingen and vennootschappen don't need it, we allow the memberships to be empty then.
1. Create 2 new organisations:
- vennootschap
- vereniging
2. Fill in the required fields
3. Save and verify that the organisations get created successfully without the validations failing.
> fix: loosen up membership validations for vereniging en vennootschap

- package-lock.json
- package.json
The ember-inspector plugin's data tab was broken due an error occurring when
trying to access it:
```
Error message: Could not find module `@embroider/macros` imported from `frontend-organization-portal/data-adapter`
Stack trace: missingModule@http://localhost:4200/assets/vendor.js:266:11
```
Adding `@embroider/macros` as a dependency resolves this issue and allows to use
the data functionality of ember-inspector again.
Credit to @windvis debugging this issue.
> fix: add embroider/macros as dependency

- app/controllers/organizations/organization/related-organizations/edit.js
The bug fix in #642 was applied too broadly. The `save` function relies on the
information in the `memberships` array to persist the necessary changes.
Consequently, removing elements from this array results in any changes,
including their deletion, to be forgotten.
We do explicitly remove new, not yet persisted, memberships from the array and
immediately destroy them. Otherwise, they can cause failed validations, they can
be incomplete, or cause errors being thrown.
- OP-3406
- OP-3371
> fix: prevent the deletion of a membership being forgotten

- app/controllers/organizations/organization/related-organizations/edit.js
- app/models/membership.js
- tests/unit/models/membership-test.js
Add functionality to prevent that users can add duplicate relationships between
organizations.
It should not be allowed that users add duplicate relations between
organizations. In this context, duplicate relationships mean `membership`s that
have the same `member`, `organization`, and `role`. Previously, there was no
check on this and they would just be saved to the triplestore.
Before actually saving the (edited) memberships, filter out any duplicate
memberships such that they are not persisted to the triplestore. This does not
require any user interaction (beyond clicking the save button).
Note: the functionality initially requested was to show error messages to the
user informing them of duplicate relationships, and letting them resolve these
errors themselves. This was later on …
> fix: do not save duplicate relationships between organizations

- app/templates/organizations/index.hbs
- app/templates/people/index.hbs
OP-3385
Fix typo 'meldt' -> 'meld'
> fix: 'meldt' typo

- app/constants/memberships.js
- tests/unit/models/organization-test.js
The allowed "has a relation with" memberships contained two errors which are fixed by this PR.
Previously it was allowed for municipalities and provinces to be assigned as
either `organization` or `membner` in memberships concerning these two kinds of
organizations. More precisely, memberships with the following assignments were
both allowed:
| organization | member       |
|--------------|--------------|
| municipality | province     |
| province     | municipality |
Only the latter should be allowed. The former was removed as an allowed "has a
relation with" membership.
Previously a province could only be related to PEVA provinces. This is extended
to also include PEVA municipalities.
> fix: corrections to allowed "has a relation with" memberships

- config/environment.js
This enables the edit contact data when the frontend is running in a development environment. This is in addition to the environment variable set in https://github.com/lblod/app-organization-portal/pull/457 which only affects the frontend that is part of the stack and not a locally built one.
> chore: enable contact data editing in development environment

- app/routes/organizations/organization/governing-bodies/governing-body/index.js
For some harvested persons Loket contains, and produces, a duplicate given
and/or family names. For instance, a person's given name might be stored twice,
once with a language and once without a language tag. This data is in turn
consumed by OP, where the frontend does not handle these duplicate names
properly.
The mandates page for a worship service's governing body contains tables with
mandates and functionaries. When sorting such a table by given or family name
extra rows will appear when there are duplicate name triples for the person.
Steps to reproduce
1. Launch a local OP stack with PROD data (Note: use the master branch)
2. Log in as a worship user
3. Navigate to a worship service that is affected (examples in the ticket)
4. Go to the "Bestuursorganen" (Eng. Governing bodies) tab …
> fix: filter duplicate worship mandatories in route

- app/components/classification-multiple-select.js
- app/routes/organizations/organization/governing-bodies/governing-body/index.js
This filter is supposed to show all classification types by default, but due to the default pagination some of the items were missing. This adjusts the page size to the specific amount we need since the total amount of classifications is limited and known in advance.
> [OP-3384] Fix an issue with the "Type" filter on the organizations page

- app/modifiers/yasgui.js
- app/router.js
- ember-cli-build.js
- package-lock.json
- package.json
Embroider makes it possible to enable route splitting which generates bundles for each configured route. Anything that is only used by a single route will be part of a new bundle which gets loaded when the route is first accessed.
Builds on #658 so that needs to be merged first. I've split it off to make it easier to review.
<details>
<summary>Bundle size without route splitting</summary>
```
- dist/assets/chunk.271abc39a59af301148b.js: 3.04 MB (798.83 kB gzipped)
- dist/assets/chunk.f659b130de506660e966.js: 1.05 MB (294.22 kB gzipped)
- dist/assets/chunk.b800ef513827034f4ec9.js: 8.14 kB (2.94 kB gzipped)
- dist/assets/vendor.72dc14e46dc372212b850c951e74daae.js: 5.66 kB (2.28 kB gzipped)
- dist/assets/chunk.1c28d157e1a20b2387dd.js: 185 B (149 B gzipped)
- …
```
> [OP-3486] Enable route splitting

- app/routes/organizations/organization/change-events/details.js
- app/templates/organizations/organization/change-events/details/edit.hbs
- app/templates/organizations/organization/change-events/details/index.hbs
The 2025 municipality mergers introduce new scenario where a single merger change event has multiple resulting organisations (see backend [PR](https://github.com/lblod/app-organization-portal/pull/482)). Specifically, the municipality Borsbeek and Antwerpen merge, resulting in a new **district** Borsbeek that is part of the Antwerpen municipality.
The pages to view and edit the details of a change event only display the first resulting organisation.
Make the view and edit change event details display **all** resulting organisations for a change event. The implementation is similar to how original organisations are listed. This change has an additional advantage of simplifying the route's model.
For already existing merger change events with only one resulting organisations, all of them, …
> feat: display all resulting organisations for merger change events

- app/routes/organizations/organization/governing-bodies/governing-body/index.js
In #656 a workaround was applied to filter the double entries from the several
positions tables for the governing bodies for organisations. This was intended
as a quick fix until the underlying data issues could be solved. But this
workaround broke the table's pagination which was in turn fixed in #663. The
disadvantage is that the numbers displayed underneath the table will no longer
be accurate in case entries were filtered by the first workaround.
After discussing the options with business, it was decided to remove both the
original workaround and the pagination fix that was applied on top of it. A more
permanent fix of the underlying data is underway.
1. Launch a local OP stack, the example organisations used below assume you use
PROD data (note: be sure use the master branch)
2. …
> [OP-3538]: Revert fixes for positions tables

- app/components/organization-select.hbs
- app/components/organization-select.js
- app/models/organization.js
OP-3539
Show the KBO number for orgs in the org dropdown (as used in change events).
1. Log in as `Josephine WorshipEditeerder`
2. Go to organisaties
3. Select a random org, go to `veranderingsgebeurtenissen` and create a new one
4. Choose `Wijziging gebiedsomgeving` for example
5. At the bottom the field `Betrokken organisatie` will appear, this should now show KBO numbers of the orgs.
> [OP-3539]: show kbo numbers for organizations in the dropdown

- app/components/confirm-relation-with-inactive-organization-modal.hbs
- app/components/organization-select.js
- app/controllers/organizations/organization/local-involvements/edit.js
- app/models/organization-status-code.js
- app/models/organization.js
- app/templates/organizations/organization/local-involvements/edit.hbs
This adds functionality to warn a worship user when they add a local involvement with a non-active municipality or province. When a user selects a non-active organisation a popup warns them of this and asks to either explicitly confirm or cancel. Note, in this context "non-active" means any organisation that does not have the status active (*nl. Actief*), currently this means organisations that are inactive (*nl. Niet Actief*) or in formation (*nl. In oprichting*).
When a user selects an active municipality or province the behaviour remains unchanged and no popup should appear.
1. Launch a local instance of the backend using https://github.com/lblod/app-organization-portal/pull/519 . Otherwise worship users cannot read the status of a municipality or province and this new functionality …
> feat: require confirmation to add a local involvement with an non-active organisation

- app/controllers/organizations/new.js
- app/controllers/organizations/organization/core-data/edit.js
- app/controllers/organizations/organization/sites/new.js
- app/controllers/organizations/organization/sites/site/edit.js
- app/helpers/tel-format.js
- app/models/contact-point.js
- app/utils/transform-phone-numbers.js
- tests/unit/helpers/tel-format-test.js
Based on the [`tel-format` helper](https://github.com/lblod/frontend-contactgegevens-loket/blob/78ab121f0e2807695f01e6edaed6dc23dda3a2fe/app/helpers/tel-format.js) in contactgegevens-loket.
> [OP-3563] Human readable phone numbers

- app/components/edit-card/item.hbs
- app/components/phone-input.hbs
- app/components/phone-input.js
- app/components/phone-input/input.hbs
- app/components/phone-input/input.js
- app/components/site/contact-edit-card.hbs
- app/modifiers/inputmaskTel.js
- Allow entry of phone numbers without a `+`, so special numbers can be entered
- display warnings when users enter unusually short, unusually long or numbers not in the international notation.
> [OP-3601] Improve the phone input experience

- app/components/site/contact-edit-card.hbs
- app/components/site/contact-edit-card.js
- app/controllers/organizations/new.js
- app/controllers/organizations/organization/core-data/edit.js
- app/controllers/organizations/organization/sites/new.js
- app/controllers/organizations/organization/sites/site/edit.js
- app/models/address.js
- app/routes/organizations/organization/core-data/index.js
[OP-3638]
The decision taken to handle provinces for addresses outside of Flanders states that:
- we shouldn't link a province to addresses outside of Flanders
- we should be able to manually enter addresses outside of Flanders (and even outside of Belgium)
- a province is still mandatory for addresses within Flanders
This PR aims to update the validations for provinces to make it mandatory only when the address is in Flanders.
Create a new site and try different options: other country, Belgium, postcode in Flanders, outside of Flanders, to see if the province is made mandatory or not by the validation rules. It should only be mandatory within Flanders. The filed should be hidden in all the other cases, and the province shouldn't be required to be able to save the site.
> Handle addresses outside flanders better

- app/components/site/contact-edit-card.js
- app/components/trim-input.js
OP-3655
When tabbing through the contact edit card, an unchanged postal code will still trigger the clearing of municipality and province, even if it's not changed. So added a small check.
Since the postcode is inside a `TrimInput` component, this seemed like the easiest option to fix the bug since the `{{on "focusout" (perform this.trimInput)}}` will get triggered.
> [OP-3655] don't clear the address when postcode value is unchanged
