lblod/frontend-organization-portal

app/components/navigation-bar.hbs
app/helpers/is-last.js
app/styles/_breadcrumbs.scss
app/styles/app.scss
app/templates/administrative-units.hbs
app/templates/people.hbs
package-lock.json
package.json
tests/integration/helpers/is-last-test.js

This replaces @bagaar/ember-breadcrumbs with ember-breadcrumb-trail since it doesn't support FastBoot.

breadcrumbs improvements

---

app/components/table-message.hbs
app/controllers/people/index.js
app/styles/app.scss
app/styles/components/_table-message.scss
app/templates/people/index.hbs

Add a styled "no results" message to the people search page

---

app/controllers/administrative-units/index.js
app/routes/administrative-units/index.js
app/templates/administrative-units/index.hbs

Builds on the changes in #22 so that should be merged first.

Add a "no data" message to the administrative units page

---

app/templates/application.hbs
config/environment.js

Small change that updates the page title to "Organisatieportaal" as well.

Change application name to "Organisatieportaal"

---

app/router.js

The app interface only supports Dutch at the moment so having English urls is a bit strange.

Use Dutch route paths

---

app/components/navigation-bar.hbs
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/sites/index.hbs
app/templates/administrative-units/index.hbs
app/templates/index.hbs
app/templates/people/index.hbs
app/templates/people/person.hbs
package-lock.json
package.json

This release includes new button skins for the `<AuLink>` component :tada:.

Update to ember-appuniversum v0.4.5

---

app/router.js

This seems to have gone lost during a merge somewhere.

Add the positions page to the router.js file

---

app/components/sidebar-container.hbs
app/styles/app.scss
app/styles/components/_sidebar-container.scss
app/templates/administrative-units.hbs
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs
app/templates/administrative-units/administrative-unit/sites/index.hbs
app/templates/administrative-units/index.hbs
app/templates/application.hbs
app/templates/index.hbs
app/templates/people.hbs
app/templates/people/index.hbs
app/templates/people/person.hbs
app/templates/people/person/personal-information.hbs
app/templates/people/person/positions/index.hbs

This updates all the template files to prevent scrolling issues.
Based on the fix edit PR since that included some layout changed as well. I'll rebase once that's merged.
Only the last 2 commits need to be reviewed.

Layout improvements to prevent scrolling issues

---

app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs

This fixes some invalid table markup.
This slipped through the code reviewing :grin:.

Wrap the `<GoverningBodyStatus>` component in a td

---

app/templates/people/person/positions/position/index.hbs

Change to the correct attribute name for address in the contact model.

Fix address attribute in the contact model

---

app/helpers/params-for.js
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies.hbs
app/templates/administrative-units/administrative-unit/sites.hbs
app/templates/people/person.hbs
app/templates/people/person/positions.hbs
app/templates/people/person/positions/position.hbs

Defining breadcrumbs becomes a bit more boilerplatey, but the `params-for` helper should help with that a bit.

Fix breadcrumbs navigation error

---

app/components/card-grid.hbs
app/components/data-card.hbs
app/components/data-card/item.hbs
app/components/edit-card.hbs
app/components/edit-card/item.hbs
app/styles/app.scss
app/styles/components/_cards.scss

These components can be used to layout the cards on the details and edit pages.
I'll create a follow up pr which uses the data card on the administrative unit edit page already.

Create new card components

---

app/models/site-type.js
app/models/site.js
app/routes/administrative-units/administrative-unit/sites/index.js
app/routes/administrative-units/administrative-unit/sites/site.js
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/administrative-unit/sites/index.hbs

Accordingly to the last design: https://binnenland.atlassian.net/browse/OP-405 >> https://miro.com/app/board/o9J_l9uYRvM=/?moveToWidget=3074457361016755397&cot=14

Update site pages

---

app/routes/administrative-units/administrative-unit/core-data.js
app/templates/administrative-units/administrative-unit/core-data/index.hbs

- use the new `<DataCard>` component
- show the correct classification

Administrative unit core data updates

---

app/helpers/params-for.js
app/models/mandate.js
app/router.js
app/routes/administrative-units/administrative-unit/governing-bodies.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/index.js
app/routes/administrative-units/administrative-unit/governing-bodies/index.js
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs

It requires a change in the backend that is in this [PR](https://github.com/lblod/app-contact-hub/pull/20).

Governing body detail page

---

app/components/central-worship-select.hbs
app/components/central-worship-select.js
app/components/representative-body-select.hbs
app/components/representative-body-select.js
app/components/scope-select.hbs
app/components/scope-select.js
app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/routes/administrative-units/administrative-unit/core-data.js
app/routes/administrative-units/administrative-unit/core-data/edit.js
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs

- Conditional menu links for worship and central
- Show related organizations for central
- Enable to edit related organizations for worship service and part of this for central
- Enable to edit scope
- Include status date

Add conditional contents and improvements on AdminUnit edit

---

app/templates/index.hbs

Display the app version on the landings page

---

app/templates/administrative-units/administrative-unit/ministers/new.hbs

This also fixes the tab order in the contact details card.

Use the CardColumns component on the minister creation page

---

.drone.yml
Dockerfile
Dockerfile.fastboot

More information: https://docs.npmjs.com/cli/v7/commands/npm-ci

Use npm ci instead of install

---

app/models/local-involvement.js
app/models/worship-service.js
app/router.js
app/routes/administrative-units/administrative-unit/local-involvements.js
app/routes/administrative-units/administrative-unit/local-involvements/index.js
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/local-involvements.hbs
app/templates/administrative-units/administrative-unit/local-involvements/index.hbs

* Type instelling = involvements.administrativeUnit.classification.label data are empty

Add local involvments list page

---

app/components/static-page.hbs
app/controllers/contact.js
app/router.js
app/routes/contact.js
app/templates/application.hbs
app/templates/contact.hbs
app/templates/login.hbs

This refactors the login page layout into a `<StaticPage>` component and uses that to implement the contact page.

Add the contact page

---

app/controllers/contact.js
app/templates/administrative-units/administrative-unit/ministers/new.hbs
app/templates/administrative-units/administrative-unit/sites/index.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
app/templates/administrative-units/administrative-unit/sites/site/index.hbs
app/templates/administrative-units/index.hbs
app/templates/contact.hbs
app/templates/people/index.hbs
config/environment.js

https://binnenland.atlassian.net/browse/OP-438
https://binnenland.atlassian.net/browse/OP-435

Add wording change email and type

---

.drone.yml
app/components/central-worship-select.js
app/components/mandate-role-select.js
app/components/minister-position-function-select.js
app/components/municipality-select.js
app/components/province-select.js
app/components/recognized-worship-type-select.js
app/components/representative-body-select.js
app/components/scope-select.js
app/components/site-type-select.js
app/styles/app.scss
config/environment.js
package-lock.json
package.json

FastBoot seems to be incompatible with the mu.semtech auth setup.

Remove FastBoot (and Metis)

---

app/components/person-search.hbs
app/components/person-search.js
app/controllers/administrative-units/administrative-unit/ministers/new.js
app/templates/administrative-units/administrative-unit/ministers/new.hbs

This will be reused on the mandatory creation page.

Extract the person search logic into a component

---

app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/routes/administrative-units/administrative-unit/governing-bodies.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body.js
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs

I noticed the governing body breadcrumb wasn't working properly and while trying to figure out the issue I noticed how confusing the naming was, so I tried fixing that as well :grimacing:.

governing body naming refactoring and breadcrumb bug fix

---

app/templates/administrative-units/index.hbs

- added status sorting on administrative unit
Note: status sorting on person still needs to be done but I need some help with that as the filter is not yet available.

add sorting on status

---

app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js

- rename regression caused by the previous refactor (#101)
- link the address records correctly

Fix the mandatory edit page

---

.drone.yml
Dockerfile
Dockerfile.fastboot
app/templates/index.hbs
config/environment.js

This will show the commit hash (which links to github :sunglasses:) instead of the version in the dev environment. This hopefully will make things less confusing :smile:.

Show commit hash in dev environments

---

app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/controllers/administrative-units/administrative-unit/sites/site/edit.js

This replaces the duplicated full address generation logic with the util function.

Use the `combineFullAddress` util were needed

---

app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/index.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/index.js
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs

- show all the mandatories attached to each role
- fix the count in the pagination
- add sorting to the tables

Governing body details page improvements

---

app/components/page-header.hbs
app/components/person-search.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs
app/templates/administrative-units/administrative-unit/local-involvements/index.hbs
app/templates/administrative-units/administrative-unit/sites/index.hbs
app/templates/people/index.hbs
app/templates/people/person/contacts/index.hbs
app/templates/people/person/positions/index.hbs
app/templates/people/person/positions/mandatory/index.hbs
app/templates/people/person/positions/minister/index.hbs

Includes:
- Personen toevoegen
- Contactgegevens bewerken
- Posities toevoegen & bewerken
- Bestuursorganen
- Vestigingen toevoegen
- Betrokken lokale besturen
- Bedienaren

Alert for new entitites and missing functionalities

---

app/components/nationality-select.hbs
app/components/nationality-select.js
app/models/nationality.js

Need to use [this backend](https://github.com/lblod/app-contact-hub/pull/34)

Change nationality model

---

app/styles/_shame.scss
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
app/templates/administrative-units/administrative-unit/ministers/new.hbs
app/templates/administrative-units/administrative-unit/sites/new.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
app/templates/administrative-units/new.hbs

- make button labels consistent
- fix button group alignment

Consistent button labels

---

app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
app/templates/administrative-units/administrative-unit/local-involvements/index.hbs

Additional fix for the consistency of buttons:
- secondary button style and icon for all edit buttons
- primary button style for add new buttons

Consistent buttons

---

app/components/card-columns.hbs
app/components/card-grid.hbs
app/components/data-card.hbs
app/components/data-card/item.hbs
app/components/edit-card.hbs
app/components/edit-card/item.hbs
app/styles/_shame.scss
app/styles/components/_cards.scss
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/administrative-unit/sites/new.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
app/templates/administrative-units/administrative-unit/sites/site/index.hbs
app/templates/administrative-units/new.hbs

Fixes for:
- contact card consistency: follow the same order and layout for all contact details
- fix overflow of text and long urls by adding the wordbreak utility class
- keep pills on one line in data tables

Contact card consistency + small bugfixes

---

app/controllers/administrative-units/administrative-unit/ministers/index.js
app/controllers/people/person/positions/minister/edit.js
app/router.js
app/routes/people/person/positions/minister/edit.js
app/templates/administrative-units/administrative-unit/ministers/index.hbs
app/templates/people/person/positions/minister/edit.hbs
app/templates/people/person/positions/minister/index.hbs

https://www.figma.com/file/P8aIfSN0f1CctxBGYdeyKe/ERE-v1?node-id=621%3A5504

Edit minister page

---

app/components/half-election-type-select.hbs
app/components/half-election-type-select.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/models/board-position.js
app/models/mandatory.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs

This field was missing from the edit page. Now it works the same as on the creation page.

Make it possible to change the half election type of a mandate

---

app/components/app-header.hbs
app/components/app-header.js
app/components/environment-label.hbs
app/components/environment-label.js
app/styles/app.scss
app/styles/components/_environment-pill.scss
config/environment.js
package-lock.json
package.json

Adds a environment pill in the app-header (solution taken from the kaleidos project).
Additionally: 
- fixes the datepicker overflow bug by updating ember-appuniversum to 0.6.1

Add environment pill

---

app/router.js
app/routes/administrative-units/administrative-unit/legal-structures/legal-structure.js
app/routes/administrative-units/administrative-unit/legal-structures/legal-structure/index.js
app/templates/administrative-units/administrative-unit/legal-structures/index.hbs
app/templates/administrative-units/administrative-unit/legal-structures/legal-structure.hbs
app/templates/administrative-units/administrative-unit/legal-structures/legal-structure/index.hbs

https://www.figma.com/file/P8aIfSN0f1CctxBGYdeyKe/ERE-v1?node-id=964%3A685
To test it, the following dummy data are needed to be migrated (if not already done):
```
@prefix ns1: <http://www.w3.org/ns/org#> .
@prefix ns10: <https://data.vlaanderen.be/ns/generiek#> .
@prefix ns11: <http://www.w3.org/ns/regorg#> .
@prefix ns12: <http://www.w3.org/ns/adms#> .
@prefix ns13: <http://www.w3.org/2004/02/skos/core#> .
@prefix ns14: <http://data.vlaanderen.be/ns/besluit#> .
@prefix ns15: <http://mu.semte.ch/vocabularies/ext/> .
@prefix ns16: <http://purl.org/dc/terms/> .
@prefix ns17: <http://data.lblod.info/vocabularies/contacthub/> .
@prefix ns18: <http://lblod.data.gift/vocabularies/organisatie/> .
@prefix ns2: <http://mu.semte.ch/vocabularies/core/> .
@prefix ns3: …
```

Add details page of a legal structure

---

app/controllers/administrative-units/administrative-unit/legal-structures/legal-structure/edit.js
app/router.js
app/routes/administrative-units/administrative-unit/legal-structures/legal-structure/edit.js
app/templates/administrative-units/administrative-unit/legal-structures/index.hbs
app/templates/administrative-units/administrative-unit/legal-structures/legal-structure/edit.hbs
app/templates/administrative-units/administrative-unit/legal-structures/legal-structure/index.hbs
app/validations/associated-structure.js

Based on the details page design: https://www.figma.com/file/P8aIfSN0f1CctxBGYdeyKe/ERE-v1?node-id=964%3A685
Validation and editing rules: https://abb-vlaanderen.gitbook.io/doc-organisatieportaal/detail-pages/verbonden-juridische-besturen#validation-and-editing-rules
To test it, the following dummy data are needed to be migrated (if not already done):
```
@prefix ns1: <http://www.w3.org/ns/org#> .
@prefix ns10: <https://data.vlaanderen.be/ns/generiek#> .
@prefix ns11: <http://www.w3.org/ns/regorg#> .
@prefix ns12: <http://www.w3.org/ns/adms#> .
@prefix ns13: <http://www.w3.org/2004/02/skos/core#> .
@prefix ns14: <http://data.vlaanderen.be/ns/besluit#> .
@prefix ns15: <http://mu.semte.ch/vocabularies/ext/> .
@prefix ns16: <http://purl.org/dc/terms/> .
@prefix ns17: …
```

Add legal strcture edit page and validation

---

app/services/session.js
config/environment.js

It seems we forgot this when setting up ACM/IDM.

Redirect the user to the logout url after logging out

---

app/components/edit-card/item.hbs
app/components/error/kbo-number.hbs
app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/controllers/administrative-units/new.js
app/models/identifier.js
app/routes/administrative-units/administrative-unit/core-data/edit.js
app/routes/administrative-units/new.js
app/routes/people/new.js
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/new.hbs
app/validations/worship-administrative-unit.js

Also includes some other refactorings and improvements which were needed (so don't squash this PR when merging).

Validate if a KBO number is unique before saving 

---

app/controllers/administrative-units/new.js
app/models/governing-body-classification-code.js
app/models/recognized-worship-type.js

This allows users to link mandatories to the administrative unit.

Automatically create a governing body on administrative unit creation

---

app/components/datepicker.hbs
package-lock.json
package.json

~~It seems the appuniversum update causes a [style regression](https://github.com/appuniversum/ember-appuniversum/issues/156#issuecomment-972685926):~~ The issue has been fixed in ember-appuniversum v0.6.6 :tada:

Add an error state to the `<Datepicker>` component

---

CHANGELOG.md

This adds changelogs for v1.1.0 and v1.2.0 generated by lerna-changelog. I didn't went further into the PR history since v1 already had a manually written changelog.

Generate the CHANGELOG.md file

---

app/controllers/people/new.js
app/models/date-of-birth.js
app/models/person.js
app/models/request-reason.js
app/routes/people/new.js
app/services/sensitive-personal-information.js
app/templates/people/new.hbs

This uses the privacy service when creating a new person to store the data in a more secure graph. Users will first have to provide a reason before they can see this information.

Use the privacy service to store sensitive personal information

---

app/components/person-search.hbs
app/components/report-wrong-data.hbs
app/components/report-wrong-data.js
app/components/secured-area.hbs
app/components/secured-area.js
app/services/current-session.js
app/styles/_shame.scss
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs
app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs
app/templates/administrative-units/administrative-unit/local-involvements/index.hbs
app/templates/administrative-units/administrative-unit/ministers/index.hbs
app/templates/administrative-units/administrative-unit/sites/index.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
app/templates/administrative-units/administrative-unit/sites/site/index.hbs
app/templates/administrative-units/index.hbs
app/templates/people/index.hbs
app/templates/people/person/contacts/index.hbs
app/templates/people/person/personal-information/edit.hbs
app/templates/people/person/personal-information/index.hbs
app/templates/people/person/positions/index.hbs
app/templates/people/person/positions/minister/edit.hbs
app/templates/people/person/positions/minister/index.hbs

see : https://abb-vlaanderen.gitbook.io/doc-organisatieportaal/overview/editing-information-and-card-views/feature-passport-report-wrong-data

Allow users to easily report wrong data

---

app/controllers/administrative-units/administrative-unit/change-events/new.js

This ensures the organization status is in sync with the most recent change event result status.

Update organization status on creation

---

app/controllers/administrative-units/administrative-unit/change-events/new.js

The data model expects these properties to be set most of the time (with some exceptions), although it wasn't needed for the frontend to work properly.

Always set original and resulting organization when creating change events

---

app/components/static-page.hbs
app/templates/login.hbs
config/environment.js

Use the proper casing for "OrganisatiePortaal"

---

app/components/position/contact-edit-card.hbs
app/controllers/people/person/personal-information/edit.js
app/routes/people/person/personal-information/edit.js
app/templates/people/person/personal-information/edit.hbs

as discussed with Saska: "The org and position is not editable on there but the contact info should be"

Allow users to edit contact information on the person edit page

---

app/routes/people/person/personal-information.js

fix position details not shown

---

app/controllers/people/index.js
app/routes/people/index.js
app/templates/people/index.hbs

split first name / last name in filter search person

---

app/routes/people/person/personal-information/edit.js

Fix contact gegevens title not shown

---

app/routes/administrative-units/index.js

searching in field “naam” with multiple words gives no result

---

app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/controllers/administrative-units/new.js
app/controllers/people/new.js
app/controllers/people/person/personal-information.js
app/controllers/people/person/personal-information/edit.js
app/controllers/people/person/personal-information/index.js
app/controllers/people/person/personal-information/request-sensitive-data.js
app/helpers/help-text.js
app/models/request-reason.js
app/router.js
app/routes/people/person/personal-information.js
app/routes/people/person/personal-information/edit.js
app/routes/people/person/personal-information/request-sensitive-data.js
app/services/sensitive-personal-information.js
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs
app/templates/people/new.hbs
app/templates/people/person/personal-information/edit.hbs
app/templates/people/person/personal-information/index.hbs
app/templates/people/person/personal-information/request-sensitive-data.hbs
package-lock.json
package.json

Should be reviewed after:
https://github.com/lblod/privacy-centric-service/pull/3
https://github.com/lblod/app-contact-hub/pull/118

sensitive data

---

app/controllers/administrative-units/administrative-unit/core-data/index.js
app/templates/administrative-units/administrative-unit/core-data/index.hbs

Define a specific order for identifiers in core data

---

app/controllers/organizations/organization/core-data.js
app/helpers/kbo-format.js
app/helpers/rrn-format.js
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/new.hbs
app/templates/organizations/organization/core-data.hbs
app/templates/people/new.hbs
app/templates/people/person/personal-information/edit.hbs
app/templates/people/person/personal-information/index.hbs
tests/integration/helpers/kbo-format-test.js
tests/integration/helpers/rrn-format-test.js
tests/unit/controllers/organizations/organization/core-data-test.js

Solves different tickets : 
- OP-1239
- OP-1237
- OP-1240
- OP-1238

KBO & RRN interface improvements

---

app/routes/administrative-units/index.js

tested with both Sofie's and Zelim's comment => OP-1222

change the filter search for name field

---

app/services/sensitive-personal-information.js
app/templates/people/person/personal-information/edit.hbs

Bugfixes for OP-1241 & OP-1233

Fix order fields & copy sensitive info object

---

app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs
app/templates/people/new.hbs
app/templates/people/person/personal-information/edit.hbs

autocomplete off for input with mask

---

app/components/administrative-unit-select-by-name.hbs
app/components/administrative-unit-select-by-name.js
app/templates/administrative-units/index.hbs

autocomplete bestuur name with mu search

---

app/routes/administrative-units/index.js

Filter Province 'single select' shows both 'Oost-Vlaanderen' and 'West-Vlaanderen'

---

app/controllers/people/index.js
app/templates/people/index.hbs

Filter 'Organisatie' shows options with no results

---

app/controllers/people/new-position.js
app/templates/people/new-position.hbs

Able to create minister position for central worship services

---

app/components/administrative-unit-select-by-name.js

type a part of a word and not preselect an option

---

app/controllers/people/person/personal-information/index.js
app/services/sensitive-personal-information.js

Bugfixes for OP-1250 & OP-1251

typo fixes for sensitive info

---

app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
app/templates/organizations/organization/core-data.hbs

fix status

---

app/controllers/administrative-units/index.js
app/controllers/people/index.js
app/routes/administrative-units/index.js
app/routes/people/index.js
app/templates/administrative-units/index.hbs
app/templates/people/index.hbs

 Add reset button and remove research button

---

app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
app/templates/organizations/organization/index.hbs

hotfix for OP-1259
as master is 1.7.0 and this has already changed a lot since 1.6.4, another fix is needed for master / development (so this shouldn't be merge but just tagged as a hotfix I think?)

hotfix 1.6.5 status

---

app/components/position-select.js

show all position filter

---

app/routes/administrative-units/index.js

fix feature municipality

---

app/controllers/administrative-units/index.js
app/controllers/people/index.js
app/routes/administrative-units/index.js
app/routes/people/index.js
app/templates/administrative-units/index.hbs
app/templates/people/index.hbs

Reverts lblod/frontend-organization-portal#298
After Saska's input, it might be a bad idea UX-wise to remove the search button. It's still under discussion what is expected. In the meantime, we revert this PR.

Revert " Add reset button and remove research button"

---

app/templates/administrative-units/administrative-unit/related-organizations/index.hbs

Fix appearance of related organizations page

---

app/templates/people/person/positions/index.hbs

Remove warning on position page

---

app/components/administrative-unit-select-by-name.js
app/components/person-search-by-name.hbs
app/components/person-search-by-name.js
app/components/person-search.hbs
app/components/person-search.js

autosuggestion person

---

app/components/person-search-by-name.js

OP-1265 => fix Sofie's comment

Remove duplicates in person search result

---

app/controllers/administrative-units/administrative-unit/local-involvements/index.js
app/routes/administrative-units/administrative-unit/local-involvements/index.js
app/templates/administrative-units/administrative-unit/local-involvements/index.hbs

Fix table navigation for betrokken locale besturen

---

app/templates/organizations/organization/related-organizations.hbs

Show table loading results instead of hiding it

---

app/controllers/administrative-units/index.js
app/controllers/people/index.js
app/templates/administrative-units/index.hbs
app/templates/people/index.hbs

New version of #298, but keeping the `search` button ! (OP-893)

Add button to reset filters

---

app/components/administrative-unit-select-by-name.js
app/components/administrative-unit-select.js
app/components/classification-select.hbs
app/components/classification-select.js
app/components/municipality-select.hbs
app/components/municipality-select.js
app/components/position-select.hbs
app/components/position-select.js
app/components/province-select.hbs
app/components/province-select.js
app/components/recognized-worship-type-select.hbs
app/components/recognized-worship-type-select.js
app/controllers/administrative-units/new.js
app/models/administrative-unit-classification-code.js
app/models/board-position.js
app/models/minister-position.js
app/models/recognized-worship-type.js
app/routes/administrative-units/index.js
app/templates/administrative-units/index.hbs
app/templates/people/index.hbs
package-lock.json
package.json

About OP-1274
Feature passeport : https://abb-vlaanderen.gitbook.io/doc-organisatieportaal/data/fp-contextual-dropdown-lists-worship-services
Goes with https://github.com/lblod/app-organization-portal/pull/130
Big PR, don't hesitate to be picky ! ;)

Contextual dropdowns for filters

---

app/controllers/people/index.js
app/services/mu-search.js
app/templates/people/index.hbs

Sort names depending on insert

---

app/components/person-search.js

Sort persons in new position

---

app/components/person-search.js

Fix positions not saved

---

app/components/municipality-select.js

Increase size page when filtering municipalities

---

app/components/address-register-bus-number-selector.hbs
app/components/address-register-selector.hbs
app/components/contact-details.hbs
app/components/contact-details.js
app/components/municipality-select.hbs
app/components/person-search.hbs
app/components/province-select.hbs
app/components/site/contact-edit-card.hbs
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/controllers/administrative-units/administrative-unit/ministers/new.js
app/controllers/people/person/personal-information/edit.js
app/controllers/people/person/positions/minister/edit.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/routes/administrative-units/administrative-unit/ministers/new.js
app/routes/people/person/personal-information.js
app/routes/people/person/personal-information/edit.js
app/routes/people/person/positions/minister/edit.js
app/services/contact-details.js
app/styles/_shame.scss
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
app/templates/administrative-units/administrative-unit/ministers/new.hbs
app/templates/people/person/personal-information/edit.hbs
app/templates/people/person/positions/minister/edit.hbs
package-lock.json
package.json

Goal of this POC is to deploy a working example on dev. I tested it locally but I'd really appreciate a second look before deploying it; design is different than on figma, this is normal (will be finalize after demo it to Saska & Sofie)

copy mechanism poc

---

app/routes/administrative-units/administrative-unit/governing-bodies.js

sort governing bodies by period

---

app/controllers/people/new.js
app/controllers/people/person/personal-information/edit.js
app/templates/people/new.hbs
app/templates/people/person/personal-information/edit.hbs

adjusted date picker for birthdate

---

config/deprecation-workflow.js
package-lock.json
package.json

Bump packages and remove some deprecations

---

app/templates/administrative-units/administrative-unit/ministers/new.hbs
app/templates/people/person/positions/minister/edit.hbs
app/templates/people/person/positions/minister/index.hbs

Change wording FOD finances

---

app/components/contact-details.hbs
app/components/contact-details.js
app/components/position/contact-edit-card.hbs
app/components/propagate-contact-details-update.hbs
app/components/propagate-contact-details-update.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/controllers/administrative-units/administrative-unit/ministers/new.js
app/controllers/people/person/positions/minister/edit.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/routes/administrative-units/administrative-unit/ministers/new.js
app/services/contact-details.js
app/styles/_shame.scss
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
app/templates/people/person/positions/mandatory/index.hbs
app/templates/people/person/positions/minister/edit.hbs

Refinement poc copy mechanism

---

app/components/address-search.hbs
app/components/position/contact-edit-card.hbs
app/components/site/contact-edit-card.hbs

Move button to find address in list

---

app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.js
app/routes/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.js
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.hbs

OP-1356
I kept it very simple (two routes that are copy pastes apart from the title) because it's probably going to evolve with OP-1350 and i'm not sure how yet, I'll take the time to refactor a bit while doing this second task.

Create new routes for board member positions

---

app/validations/mandatory.js
app/validations/minister.js

validation start date & end date

---

app/components/contact-details.hbs

show full address in address column

---

app/components/contact-details.hbs
app/components/contact-details.js

Prevent users from trying to create contact info consecutively

---

app/routes/people/index.js

Person Search query : names with more than one word give no results

---

app/components/contact-details.hbs

OP-1389 & last comment of Sofie in OP-1399

Cosmetic change front-end copy mechanism

---

app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/loading.hbs

missing loading for governing body

---

app/components/address-register-bus-number-selector.hbs
app/components/organization-status-select.hbs

Enable search fields for accessibility

---

app/components/person-search.hbs

Update text shown when adding person

---

app/controllers/people/index.js
app/templates/people/index.hbs

OP-1422
I will cherry pick it in 1.8.0 if ok

link to position bugfix

---

app/components/contact-details.js

fix address on edit

---

app/components/address-register-selector.hbs
app/components/power-select/before-options-with-pre-filled-text.hbs
app/components/power-select/before-options-with-pre-filled-text.js
app/styles/_shame.scss

Add component to update already searched address

---

app/routes/administrative-units/index.js
app/routes/people/index.js
app/templates/administrative-units/index.hbs
app/templates/people/index.hbs

Enable auto search

---

app/components/datepicker.hbs
app/components/datepicker.js
app/controllers/administrative-units/administrative-unit/change-events/details/edit.js
app/controllers/administrative-units/administrative-unit/change-events/new.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/controllers/administrative-units/administrative-unit/ministers/new.js
app/controllers/people/new.js
app/controllers/people/person/personal-information/edit.js
app/controllers/people/person/positions/minister/edit.js
app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/new.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
app/templates/administrative-units/administrative-unit/ministers/new.hbs
app/templates/people/new.hbs
app/templates/people/person/personal-information/edit.hbs
app/templates/people/person/positions/minister/edit.hbs
app/utils/datepicker-validation.js

OP-1351
OP-789
OP-1313
OP-1454
OP-1455
OP-1357
translations are temporatry and will be implemented once they are defined in OP-1465

input mask for date

---

app/components/contact-details.hbs
app/components/custom-modal.hbs
app/components/custom-modal.js
package-lock.json
package.json

OP-1469
How to reproduce the bug (without the fix):
- make sure you're using Chrome 102
- open the contact details modal (edit a position)
- press either cancel or selecteer button
- the page is blocked & you can't do anything
Happens to all environments (dev, qa)
this is temporary, once the issue is fixed in appuniversum, we should do OP1474

fix bug chrome & aumodal

---

app/components/datepicker.js
app/controllers/administrative-units/administrative-unit/change-events/details/edit.js
app/controllers/administrative-units/administrative-unit/change-events/new.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/controllers/administrative-units/administrative-unit/ministers/new.js
app/controllers/people/new.js
app/controllers/people/person/personal-information/edit.js
app/controllers/people/person/positions/minister/edit.js
app/utils/datepicker.js

[OP-1468](https://binnenland.atlassian.net/browse/OP-1468)

translation datepicker

---

app/components/datepicker.hbs
app/components/datepicker.js

only show validation error when focus out

---

app/controllers/people/index.js
app/routes/people/index.js
app/templates/people/index.hbs

when open a new tab, we should be redirected to position

---

app/components/contact-details.hbs

set modal to fullscreen

---

app/components/position/contact-edit-card.hbs
app/components/site/contact-edit-card.hbs
app/components/trim-input.hbs
app/components/trim-input.js
app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/new.hbs
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
app/templates/administrative-units/new.hbs
app/templates/people/index.hbs
app/templates/people/new.hbs
app/templates/people/person/personal-information/edit.hbs

trim component

---

app/components/address-register-selector.hbs
app/components/address-register-selector.js
app/components/province-select.js

OP-1537
see video to reproduce

When changing the address consecutively, the province doesn't get auto-filled

---

app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs

fix input for percentage

---

app/components/contact-details.hbs
app/components/contact-edit-row.hbs
app/components/province-select.js

Can lose ability to select province in contact detail

---

app/components/contact-details.hbs
app/components/contact-edit-row.hbs

fix width fol columns

---

app/components/contact-details.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.js
app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/controllers/administrative-units/administrative-unit/ministers/new.js
app/controllers/people/person/positions/minister/edit.js
app/services/contact-details.js

silently discard empty addresses

---

app/validations/change-event.js

fix date error translation

---

app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.js

allContactFieldsEmpty not a function

---

app/styles/_shame.scss

Fix button position to right

---

app/controllers/administrative-units/administrative-unit/local-involvements/edit.js
app/models/involvement-type.js
app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs

only one gemeente/province with  type betrokkenheid relationship toezicht

---

.gitignore
app/controllers/administrative-units/administrative-unit/local-involvements/edit.js
app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs

leave percentage empty but editable in case of mede financiering

---

app/components/municipality-select.js

Fix classification in municilapity select

---

app/components/position-select.js

Show all positions in filter dropdown

---

app/components/site-type-select.js
app/controllers/administrative-units/administrative-unit/sites/new.js
app/controllers/administrative-units/administrative-unit/sites/site/edit.js
app/templates/administrative-units/administrative-unit/sites/new.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs

Fix logic of site types

---

app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
app/templates/administrative-units/administrative-unit/change-events/index.hbs
app/templates/administrative-units/administrative-unit/change-events/new.hbs
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/administrative-unit/executives.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs
app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
app/templates/administrative-units/administrative-unit/sites/index.hbs

Show type of admin unit in titles

---

app/controllers/administrative-units/index.js
app/templates/administrative-units/index.hbs

Show type religion column when only worship units are shown

---

app/controllers/administrative-units/administrative-unit.js
app/templates/administrative-units/administrative-unit.hbs
app/templates/people/index.hbs
app/templates/people/person/positions/agent/index.hbs
app/templates/people/person/positions/index.hbs

Hide leidinggevenden for districts

---

app/components/governing-body-status.js
app/routes/administrative-units/administrative-unit/governing-bodies.js
app/templates/administrative-units/administrative-unit/governing-bodies/index.hbs

OP-1655
I also fixed the sorting of the governing bodies

Fix logic of governing body status component

---

app/models/change-event-type.js

Remove merge option from district change events

---

app/controllers/administrative-units/administrative-unit/change-events/details/edit.js
app/controllers/administrative-units/administrative-unit/change-events/details/index.js
app/routes/administrative-units/administrative-unit/change-events/new.js
app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
app/templates/administrative-units/administrative-unit/change-events/new.hbs

Add fields for city title change event

---

app/controllers/administrative-units/administrative-unit/sites/site/edit.js
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs

force primary site if there is no primary site selected

---

app/controllers/administrative-units/administrative-unit/sites/site/edit.js
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs

warning if nor primary site

---

app/controllers/administrative-units/administrative-unit/sites/site/edit.js

OP-1697 (comment from Kevin, sorry I closed the previous PR to rebase properly)

reset error message

---

app/components/related-organizations/edit-municipality.hbs
app/components/related-organizations/edit-ocmw.hbs
app/components/related-organizations/edit-worship-service.hbs
app/templates/administrative-units/new.hbs
app/validations/administrative-unit.js

sub organization not required

---

app/controllers/administrative-units/new.js
app/models/governing-body-classification-code.js

Add back logic for orgaan type depending on religion

---

app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs

allow decimal values for financial percentage

---

app/controllers/administrative-units/administrative-unit/change-events/new.js

OCMW's don't merge when the municipalities do

---

app/models/minister-position.js

contextual dropdown update with new codelist minister position

---

app/models/minister-position.js
app/models/minister.js
app/routes/administrative-units/administrative-unit/ministers/index.js
app/templates/administrative-units/administrative-unit/ministers/index.hbs

fix empty person for bedinaeren

---

app/routes/administrative-units/administrative-unit/governing-bodies.js

hide governing bodies in the future

---

app/components/position-select.js

positions not listed

---

app/controllers/contact.js
app/styles/_shame.scss
app/templates/contact.hbs

Feat/New Contact Page

---

app/controllers/administrative-units/new.js
app/models/board-position-code.js
app/models/governing-body-classification-code.js
app/routes/administrative-units/administrative-unit/governing-bodies.js

OP-1696
Has to be tested with https://github.com/lblod/construct-administrative-unit-relationships-service/pull/1 and https://github.com/lblod/app-organization-portal/pull/189

Delegate creation of admin unit relationships to a service

---

app/components/governing-body-status.js

bestuursorganen in the future should not be active anymore

fix status logic

---

app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.js
app/controllers/people/new.js

On creating a new person follow up with linking it to a position

---

app/controllers/administrative-units/new.js

check whether scope is defined before copying

---

app/templates/people/person/personal-information/index.hbs

[OP-1956](https://binnenland.atlassian.net/browse/OP-1956)

Bug/Typo: Add letter "i" in Province - person template

---

app/styles/_shame.scss
app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/new.hbs
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/board-member/new.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/edit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/mandatory/new.hbs
app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs
app/templates/administrative-units/administrative-unit/ministers/new.hbs
app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
app/templates/administrative-units/administrative-unit/sites/new.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
app/templates/administrative-units/new.hbs
app/templates/people/new-position.hbs
app/templates/people/new.hbs
app/templates/people/person/personal-information/edit.hbs
app/templates/people/person/personal-information/request-sensitive-data.hbs
app/templates/people/person/positions/minister/edit.hbs

* [OP-1966](https://binnenland.atlassian.net/browse/OP-1966)
* Redo changes from [OP-1757](https://binnenland.atlassian.net/browse/OP-1757), required within [OP-1927](https://binnenland.atlassian.net/browse/OP-1927)

Fix - Feat/Redo change button order

---

app/models/board-position-code.js

Show Schepen positions in bestuursleden table

---

app/styles/app.scss
app/styles/components/_cards.scss
package-lock.json
package.json

* [OP-1967](https://binnenland.atlassian.net/browse/OP-1967) 
* Requirements from [OP-848](https://binnenland.atlassian.net/browse/OP-848) - Form labels are always centered vertically

Fix/Align Labels to Baseline

---

app/components/site/contact-data-card.hbs
app/components/site/contact-edit-card.hbs

Add email to primary contact info

---

app/routes/people/index.js

OP-1987
requires https://github.com/lblod/app-organization-portal/pull/207

fix missing person

---

app/validations/administrative-unit.js

Add error message for name validation

---

app/validations/administrative-unit.js

Enable org status validation

---

app/routes/administrative-units/administrative-unit/governing-bodies.js

Fix filtering organen

---

app/components/related-organizations/view-central-worship-service.hbs
app/controllers/administrative-units/administrative-unit/local-involvements/edit.js
app/controllers/administrative-units/administrative-unit/local-involvements/index.js
app/models/local-involvement.js
app/models/worship-administrative-unit.js
app/models/worship-service.js
app/routes/administrative-units/administrative-unit/local-involvements/edit.js
app/routes/administrative-units/administrative-unit/local-involvements/index.js
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs
app/templates/administrative-units/administrative-unit/local-involvements/index.hbs

Enable some local involvements for central worship services

---

app/templates/application.hbs

Update link in banner

---

app/templates/index.hbs
app/templates/login.hbs

Update text of module Personen

---

app/templates/administrative-units/administrative-unit/core-data/index.hbs

Hide regio for OCMWs

---

app/controllers/administrative-units/administrative-unit/executives/index.js
app/routes/administrative-units/administrative-unit/executives.js
app/templates/administrative-units/administrative-unit/executives.hbs

Feat / Filter on Leidinggevenden

---

app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs

Feat / Date sorting for governing bodies

---

app/models/minister-position.js

add new position

---

app/components/au-navigation-nested-link.hbs
app/components/au-navigation-nested-link.js
app/components/contact-details.hbs
app/components/datepicker.hbs
app/components/datepicker.js
app/components/navigation-bar.hbs
app/components/page-header.hbs
app/components/propagate-contact-details-update.hbs
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
package-lock.json
package.json

Use `AuDateInput` component from bumped ember-appuniversum

---

app/routes/administrative-units/administrative-unit/governing-bodies.js
package-lock.json

Allow user to see all organen periods

---

app/components/administrative-unit-select.hbs
app/components/administrative-unit-select.js
app/controllers/administrative-units/administrative-unit/local-involvements/edit.js
app/routes/administrative-units/administrative-unit/local-involvements/edit.js
app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs

only municipality for adviserende

---

app/validations/local-involvement.js

OP-2220, had to fight against ember proxies all over the place. doing a simple  change requires a Phd 😢 , but hopefully it seems working. if you see a better way please tell me because I couldn't do it otherwise

validate involvement type

---

app/templates/administrative-units/administrative-unit/local-involvements/edit.hbs

unnecessary callback as we validate the chosen involvement

---

app/routes/people/person/positions/index.js
app/services/contact-details.js
app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
app/templates/people/person/personal-information/index.hbs
app/templates/people/person/positions/index.hbs

add mandataris status

---

app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/templates/administrative-units/administrative-unit/core-data/edit.hbs

disable editing municipality province name

---

app/components/app-header.hbs
app/routes/select-role.js

select role in the user menu on the right top

---

app/controllers/administrative-units/administrative-unit/governing-bodies/governing-body/edit.js
app/validations/governing-body.js

validation error bugfix

---

app/components/site-type-select.hbs
app/controllers/administrative-units/administrative-unit/change-events/details/edit.js
app/controllers/administrative-units/administrative-unit/change-events/new.js
app/controllers/administrative-units/administrative-unit/core-data/index.js
app/controllers/administrative-units/administrative-unit/sites/new.js
app/controllers/administrative-units/administrative-unit/sites/site/edit.js
app/routes/administrative-units/administrative-unit/change-events/details/edit.js
app/routes/administrative-units/administrative-unit/related-organizations/index.js
app/routes/administrative-units/administrative-unit/sites/new.js
app/routes/administrative-units/administrative-unit/sites/site/edit.js
app/templates/administrative-units/administrative-unit.hbs
app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
app/templates/administrative-units/administrative-unit/change-events/new.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/administrative-unit/sites/new.hbs
app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
app/validations/site.js

Creating this pr that will contain more prs to avoid merge conflict when someone has time to check it out :)
this contains: 
- OP-2369 && OP-2368 "make vestigingen type mandatory"
- OP-2401 && OP-2403:  NIS code isn't applicable here
- OP-2429
- OP-2431
- OP-2423 && OP-1866
- OP-2390

Multiple prs, do not merge squash

---

app/routes/administrative-units.js
app/routes/organizations.js
app/routes/people.js

Redirect to 404 page when URI contains an unvalid UUID

---

app/components/representative-body-select.js
app/models/representative-body.js

Blacklist a RO from dropdown list

---

app/components/related-organizations/edit-agb.hbs
app/components/related-organizations/edit-apb.hbs
app/components/related-organizations/edit-central-worship-service.hbs
app/components/related-organizations/edit-municipality.hbs
app/components/related-organizations/edit-province.hbs
app/components/related-organizations/view-central-worship-service.hbs
app/components/related-organizations/view-municipality.hbs
app/components/related-organizations/view-province.hbs
app/controllers/administrative-units/administrative-unit/related-organizations/edit.js
app/routes/administrative-units/administrative-unit/related-organizations/edit.js
app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
app/templates/administrative-units/administrative-unit/related-organizations/index.hbs
app/templates/administrative-units/administrative-unit/related-organizations/loading.hbs

Fix sorting in related organizations tab

---

app/controllers/administrative-units/administrative-unit.js
app/templates/administrative-units/administrative-unit.hbs

Hide organen in menu

---

app/components/position-select.js
app/controllers/people/index.js
app/models/administrative-unit-classification-code.js
app/routes/people/index.js
app/templates/people/index.hbs
app/templates/people/person/personal-information/index.hbs
app/templates/people/person/positions/agent/index.hbs
app/templates/people/person/positions/index.hbs

Allow agb and apb in personen filters

---

app/templates/index.hbs
app/templates/login.hbs

Update text from the landing and home pages

---

app/services/contact-details.js

Fix contact point of agents not resolving

---

app/components/app-header.hbs
app/helpers/convert-role-names.js
app/templates/select-role.hbs

Text improvements regarding roles

---

app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs

Set regio as read-only for municipalities

---

app/routes/contact.js

Links in contact were not working because of this reset controller

---

app/templates/administrative-units/administrative-unit/core-data/edit.hbs

Show OVO as readonly even for worship services

---

app/components/related-organizations/view-central-worship-service.hbs
app/components/related-organizations/view-municipality.hbs
app/components/related-organizations/view-province.hbs
app/controllers/administrative-units/administrative-unit/related-organizations/index.js
app/routes/administrative-units/administrative-unit/related-organizations/index.js
app/templates/administrative-units/administrative-unit/related-organizations/index.hbs

Added a not active toggle to related organizations

---

app/controllers/administrative-units/administrative-unit/core-data/index.js
app/templates/administrative-units/administrative-unit/core-data/index.hbs

Added a warning when the expected end date has expired

---

app/controllers/administrative-units/new.js
app/templates/administrative-units/new.hbs

purpose and expected end date on new bestuur

---

app/controllers/organizations/organization/related-organizations.js
app/routes/organizations/organization/related-organizations.js
app/templates/organizations/organization/related-organizations.hbs

Add toggle on org status for ROs

---

app/components/administrative-unit-multiple-select.hbs
app/components/related-organizations/edit-igs.hbs
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs
app/validations/administrative-unit.js

Add validations for has participants in IGS

---

app/controllers/administrative-units/new.js

Fix expected end date not saving on new bestuur

---

app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs
app/validations/administrative-unit.js

Disable validation on planned end date

---

app/components/related-organizations/edit-agb.hbs
app/components/related-organizations/edit-apb.hbs

Add stars to mandatory related orgs of agbs & apbs

---

app/components/related-organizations/view-municipality.hbs
app/routes/administrative-units/administrative-unit/related-organizations/index.js

Add sorting on related participants

---

app/templates/people/person/personal-information/index.hbs
app/templates/people/person/positions/index.hbs

AGB/APB: make organisation clickable in module personen

---

app/routes/auth/logout.js
app/routes/auth/switch.js

Destroy active role on switch or logout

---

app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs
app/validations/administrative-unit.js

Make kbo number required

---

app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs

Fix sorting for bestuursleden

---

app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/controllers/administrative-units/new.js

Call ovo sync service on KBO update

---

app/components/classification-select.js
app/templates/administrative-units/new.hbs

Fix type bestuur not updating when soort erediesnt is updated

---

app/templates/administrative-units/index.hbs

fix dependency worship filter

---

app/routes/administrative-units/administrative-unit/change-events/new.js
app/validations/local-involvement.js

Fix type errors when saving

---

app/controllers/administrative-units/index.js
app/routes/administrative-units/index.js

Rewrite search query for multiple classification ids

---

app/components/site-type-select.js

Add Hoofdcommissariaat site type to PZ

---

app/components/classification-multiple-select.js
app/controllers/administrative-units/index.js
app/models/administrative-unit-classification-code.js
app/models/organization-classification-code.js
app/templates/administrative-units.hbs
app/templates/administrative-units/index.hbs
app/templates/index.hbs
app/templates/login.hbs
app/utils/classification-identifiers.js

OP-2787 frontend part. this is not complete as I would suggest we should maybe rename everything named with "administrative-unit-***" by something more generic

generic orgs

---

app/components/classification-multiple-select.js
app/controllers/administrative-units/index.js
app/models/administrative-unit-classification-code.js
app/templates/administrative-units/index.hbs

Include ROs to religion filter

---

app/routes/people/index.js
app/templates/people/index.hbs
app/templates/people/person/personal-information/index.hbs
app/templates/people/person/positions/index.hbs

Make all organizations clickable in persons module

---

app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/administrative-units/new.hbs

Hide purpose and planned end date when not filled in

---

app/validations/secondary-contact-point.js

added regex

---

app/templates/index.hbs
app/templates/login.hbs

| Before | After |
| ------ | ------ |
| ![image](https://github.com/lblod/frontend-organization-portal/assets/3050307/bc231e54-66a3-41fe-b87c-378dd8fe6723) | ![image](https://github.com/lblod/frontend-organization-portal/assets/3050307/22b522e7-b752-49b2-a0ad-be1945c31f33)
| Before | After |
| ------ | ------ |
| ![image](https://github.com/lblod/frontend-organization-portal/assets/3050307/8014b275-a750-4ec0-9f1b-d107d0bed6c6) | ![image](https://github.com/lblod/frontend-organization-portal/assets/3050307/924bdca0-33e7-4a0a-a1e0-f0323f202f21)

Update organization-related information in templates

---

app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/controllers/administrative-units/new.js
app/routes/administrative-units/administrative-unit/core-data/edit.js
app/routes/administrative-units/new.js
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs
app/validations/administrative-unit.js

OP-2461
Not a dutch speaker so feel free to change my validation message for a more gramatically correct one thanks

Add validation so the sharepoint is always a number

---

app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/controllers/administrative-units/administrative-unit/sites/site/edit.js

Related to OP-2974
Replace remaining `isDirty` provided by `ember-changeset` by `hasDirtyAttributes`.

Fix address and contact saving

---

app/models/address.js
app/models/change-event.js
app/models/contact-point.js
app/models/organization.js
app/models/site.js
app/models/worship-service.js
app/validators/schema.js

Related to OP-3045
Cherry-pick 2dc3e933d2a19d9851adaea7f517697397d03e71 the fix made during https://github.com/lblod/frontend-organization-portal/pull/579.

Fix null value in optional string input

---

app/helpers/help-text.js
app/templates/administrative-units/administrative-unit/core-data/edit.hbs
app/templates/administrative-units/new.hbs

Fix: names help text

---

app/models/worship-administrative-unit.js
tests/unit/models/central-worship-service-test.js
tests/unit/models/worship-service-test.js

fix: require recognised worship type for central worship services

---

README.md
app/controllers/administrative-units/administrative-unit/core-data/edit.js
app/controllers/administrative-units/new.js
app/templates/administrative-units/administrative-unit/core-data/index.hbs
app/templates/organizations/organization/core-data.hbs
config/environment.js

Remove the kbo-data feature flag.
Related to OP-3238

Remove `kbo-data-tab` feature flag

---

app/controllers/organizations/new.js

Related to OP-3230
Corresponding backend PR: https://github.com/lblod/app-organization-portal/pull/429

refactor: call relationship service using new name

---

app/controllers/organizations/organization/executives.js
app/routes/organizations/organization/executives.js
app/routes/organizations/organization/governing-bodies/governing-body/index.js
app/templates/organizations/organization/executives.hbs

There were some pages where the pagination wasn't working as expected, which resulted in not all data being accessible (anymore).
- OP-3536

[OP-3536] Fix some pagination issues
